// Affinity Brand Tracking - Data Layer
// Tracks cultural affinities across Sport, Style, and Entertainment
// to inform Crocs partnership, campaign, and creative strategy
// Last updated: March 12, 2026

const AFFINITY_ITEMS = [

  // ─── SPORT ────────────────────────────────────────────────────────────────

  {
    id: "caitlin-clark-wnba",
    category: "sport",
    type: "celebrity",
    name: "Caitlin Clark",
    description: "Clark has single-handedly transformed women's basketball. Her 2025-26 WNBA season broke every viewership record, with Indiana Fever averaging 1.2M viewers per game. Her crossover to casual fans — especially young women — is unprecedented. She already has a Nike deal and wears expressive footwear off-court. High authenticity, mass reach, and a fan base that indexes heavily against Crocs' core Gen Z and young millennial demo.",
    relevanceScore: 96,
    trendStrength: 94,
    tags: ["WNBA", "women's sports", "Gen Z", "Nike collab risk", "partnership", "cultural moment"],
    source: "ESPN / AP / Nielsen Sports",
    date: "2026-02-15",
  },
  {
    id: "lionel-messi-mls",
    category: "sport",
    type: "celebrity",
    name: "Lionel Messi – Inter Miami",
    description: "Messi's third full MLS season continues to pull unprecedented attention to American soccer. Inter Miami games routinely sell out in secondary markets for 3–5x face value. His cultural gravitational pull extends beyond sports — he drives fashion, travel, and lifestyle trends. Global appeal (especially LatAm and Europe) aligns with Crocs' international growth markets. Messi himself has been seen in slides and comfort footwear off-pitch.",
    relevanceScore: 88,
    trendStrength: 82,
    tags: ["soccer", "MLS", "LatAm", "global icon", "lifestyle", "family-friendly"],
    source: "MLS / Apple TV / ESPN Deportes",
    date: "2026-02-20",
  },
  {
    id: "lebron-james-lakers",
    category: "sport",
    type: "celebrity",
    name: "LeBron James",
    description: "LeBron's cultural footprint transcends basketball. With Bronny now starting alongside him and the father-son narrative dominating sports media, he's hitting a new cultural peak as a family man icon. His SpringHill Company continues to produce cultural content. LeBron has publicly worn Crocs in candid moments, and the Brand has good organic affinity here. A formal ambassador play or limited collab would be credible.",
    relevanceScore: 85,
    trendStrength: 76,
    tags: ["NBA", "family", "cultural icon", "SpringHill", "authentic", "comfort footwear"],
    source: "ESPN / The Athletic / X",
    date: "2026-01-30",
  },
  {
    id: "simone-biles-comeback",
    category: "sport",
    type: "celebrity",
    name: "Simone Biles",
    description: "Post-Paris Olympics, Biles has transitioned into an era of brand-building and advocacy. Her message around mental health, self-expression, and authenticity maps directly to Crocs' 'Come As You Are' ethos. She's vocal about wearing comfortable, expressive clothing and footwear in her off-hours. Younger Gen Z female audience sees her as the definitive symbol of 'unbothered excellence.' A natural Crocs fit.",
    relevanceScore: 93,
    trendStrength: 88,
    tags: ["gymnastics", "Olympics", "mental health", "Gen Z women", "self-expression", "authenticity"],
    source: "Team USA / ESPN / People",
    date: "2026-01-22",
  },
  {
    id: "pickleball-boom",
    category: "sport",
    type: "trend",
    name: "Pickleball Nation",
    description: "Pickleball is now the fastest-growing sport in the US for the third year running, with 50M+ players. Critically for Crocs, the sport skews toward comfort-forward footwear — players routinely wear casual shoes. The sport's social scene, post-match culture, and accessibility messaging are nearly identical to Crocs brand values. A 'Crocs for Pickleball' play (custom court Jibbitz set, community campaign) is highly ownable.",
    relevanceScore: 89,
    trendStrength: 91,
    tags: ["pickleball", "grassroots", "community", "cross-marketing", "footwear fit", "lifestyle sport"],
    source: "USA Pickleball / Sports & Fitness Industry Association",
    date: "2026-02-01",
  },
  {
    id: "womens-sports-viewership",
    category: "sport",
    type: "trend",
    name: "Women's Sports Viewership Surge",
    description: "2025 was the breakout year for women's sports across the board: WNBA, NWSL, college basketball, and women's tennis all hit record viewership. Brand investment is lagging demand by 2–3 years, creating a major white-space opportunity. Crocs has already built genuine cultural currency with women ages 18–35, making it a credible player in this space — where Nike and Adidas have moved slowly.",
    relevanceScore: 91,
    trendStrength: 90,
    tags: ["women's sports", "WNBA", "NWSL", "brand opportunity", "Gen Z women", "underinvested space"],
    source: "Nielsen / SponsorUnited / Sports Business Journal",
    date: "2026-02-10",
  },
  {
    id: "nil-deals-athletes",
    category: "sport",
    type: "trend",
    name: "NIL College Athlete Economy",
    description: "The NIL (Name, Image, Likeness) market has matured into a $1B+ industry. Top college athletes command $500K–$2M deals but bring enormous authentic reach with fan bases that are almost entirely Gen Z. The cost-to-reach ratio is dramatically better than pro deals. Crocs has room to build a portfolio of 10–20 college athlete partners spanning basketball, gymnastics, soccer, and swimming — categories where Crocs already has grassroots credibility.",
    relevanceScore: 84,
    trendStrength: 86,
    tags: ["NIL", "college athletes", "Gen Z", "authentic", "cost-efficient", "basketball", "gymnastics"],
    source: "Opendorse / Boardroom / On3",
    date: "2026-01-15",
  },
  {
    id: "la-2028-countdown",
    category: "sport",
    type: "news",
    name: "LA 2028 Olympics – Brand Planning Window Open",
    description: "With just over 2 years to LA 2028, brand sponsorship windows are actively opening now. This is the most commercially valuable Olympics in history for US brands — home soil, massive domestic audience, and a city (LA) synonymous with pop culture and style. USOC and USOPC athlete partnership deals are being locked in now. Crocs has a 2-year runway to build a credible 'athletes' comfort shoe of choice' narrative and position for an official or adjacent Olympic moment.",
    relevanceScore: 82,
    trendStrength: 78,
    tags: ["Olympics", "LA 2028", "planning horizon", "athlete partnerships", "brand strategy", "home soil"],
    source: "USOPC / Sports Business Journal / Adweek",
    date: "2026-03-01",
  },
  {
    id: "travis-kelce-post-nfl",
    category: "sport",
    type: "celebrity",
    name: "Travis Kelce – Full Entertainment Pivot",
    description: "With his NFL career now behind him, Kelce has fully transitioned into a media and entertainment personality. New Heights podcast pulls 4M+ weekly listeners, he has a production deal, and his celebrity profile has never been higher. Post-retirement, he's no longer constrained by NFL brand restrictions and is actively expanding his endorsement portfolio. His crossover audience — sports fans, millennial women, comedy fans — is almost perfectly aligned with Crocs' demo. A formal partnership is now more achievable than ever.",
    relevanceScore: 89,
    trendStrength: 83,
    tags: ["NFL", "entertainment crossover", "podcast", "post-retirement", "endorsement opportunity", "comedy"],
    source: "New Heights Podcast / People / Variety",
    date: "2026-03-05",
  },
  {
    id: "skateboarding-gen-alpha",
    category: "sport",
    type: "trend",
    name: "Skateboarding Gen Alpha Resurgence",
    description: "Skateboarding is experiencing a new wave, driven by Gen Alpha (born 2013+) discovering the sport through social media and the Olympics. Skate culture has always been about self-expression and anti-conformity — the same DNA as Crocs' brand. Several notable skaters have been spotted wearing Classic Clogs off the board. The skate community's embrace of 'ugly-cool' aesthetics is a direct Crocs affinity signal.",
    relevanceScore: 80,
    trendStrength: 77,
    tags: ["skateboarding", "Gen Alpha", "ugly-cool", "self-expression", "Olympic sport", "street culture"],
    source: "Thrasher / Transworld Skateboarding / TikTok",
    date: "2026-01-28",
  },

  {
    id: "march-madness-2026",
    category: "sport",
    type: "news",
    name: "March Madness 2026 – Cultural Moment",
    description: "NCAA March Madness is in full swing and dominating sports conversation. College basketball's annual moment brings together the widest cross-section of American sports fans — casual viewers, Gen Z students, families, and alumni communities. Brands that activate in real time during the tournament consistently see outsized engagement. With Crocs' NIL roster, there's an opportunity for athlete-driven bracket challenge content that's authentic, timely, and low-cost.",
    relevanceScore: 83,
    trendStrength: 92,
    tags: ["March Madness", "NCAA", "college basketball", "real-time marketing", "NIL athletes", "bracket", "Gen Z"],
    source: "NCAA / ESPN / Sporting News",
    date: "2026-03-10",
  },

  // ─── STYLE (FASHION) ──────────────────────────────────────────────────────

  {
    id: "zendaya-fashion-moment",
    category: "style",
    type: "celebrity",
    name: "Zendaya – Defining Gen Z Fashion",
    description: "Zendaya is the single most-referenced style icon among 18–28 year olds globally. Her Challengers press tour cemented her as a fashion auteur, not just an actress. She regularly bridges high fashion and approachable aesthetics — her Valentino campaign showed she's comfortable with maximalist, expressive fashion adjacent to Crocs' territory. A Zendaya Crocs collab would be a cultural earthquake. No formal relationship exists yet.",
    relevanceScore: 95,
    trendStrength: 90,
    tags: ["Gen Z icon", "fashion", "Valentino", "Challengers", "high-low fashion", "celebrity collab"],
    source: "Vogue / WWD / People",
    date: "2026-02-12",
  },
  {
    id: "sabrina-carpenter-aesthetic",
    category: "style",
    type: "celebrity",
    name: "Sabrina Carpenter – The \"Girly\" Aesthetic",
    description: "Carpenter's 2025–26 era has made her the defining aesthetic icon of the 'hyper-feminine, unserious, fun' movement. Her style — bows, pastels, platform shoes, retro silhouettes — has driven massive consumer trends from the teen to early-millennial segment. Her Short n' Sweet album era drove 400M+ TikTok videos of fans recreating her looks. Crocs' pastel colorways and playful brand voice are a natural stylistic alignment.",
    relevanceScore: 91,
    trendStrength: 92,
    tags: ["pop music", "girly aesthetic", "bows", "pastels", "Gen Z women", "fun fashion", "TikTok"],
    source: "Billboard / Vogue / TikTok",
    date: "2026-02-18",
  },
  {
    id: "gorpcore-outdoors",
    category: "style",
    type: "trend",
    name: "Gorpcore Peak",
    description: "Gorpcore — utilitarian outdoor aesthetics worn as streetwear — has fully mainstreamed. Arc'teryx, Salomon, and Merrell are in every fashion editorial. Crocs occupies a unique adjacent position: practical, durable, and increasingly seen as a 'gorpcore-lite' choice, especially with the All-Terrain and LiteRide lines. Leaning into the functional-fashion positioning in outdoor/adventure styling content could steal meaningful share of voice in this crowded trend.",
    relevanceScore: 83,
    trendStrength: 80,
    tags: ["gorpcore", "outdoor fashion", "Arc'teryx", "functional fashion", "streetwear", "LiteRide", "all-terrain"],
    source: "GQ / Highsnobiety / Vogue",
    date: "2026-01-20",
  },
  {
    id: "quiet-luxury-backlash",
    category: "style",
    type: "trend",
    name: "Quiet Luxury Fatigue & Loud Joy Rebound",
    description: "Quiet luxury had its moment (2023–2024), but 2025–26 has seen a strong consumer backlash. 'Loud Joy' — bright colors, playful accessories, unabashed personality — is the counter-movement driving social media. This is the single most favorable macro-fashion trend for Crocs in years. The brand's unapologetic 'ugly-beautiful' positioning is exactly what this moment calls for. Time to be loud.",
    relevanceScore: 90,
    trendStrength: 87,
    tags: ["quiet luxury backlash", "loud joy", "color", "self-expression", "brand moment", "macro trend"],
    source: "Business of Fashion / Vogue / Refinery29",
    date: "2026-01-30",
  },
  {
    id: "pharrell-lv-men",
    category: "style",
    type: "celebrity",
    name: "Pharrell Williams at Louis Vuitton",
    description: "Pharrell's second full year as LV Men's Creative Director has been a master class in merging streetwear, luxury, and playful expression. His Nigo collaboration and the ongoing Happy/Joyful brand messaging has cultural overlap with Crocs. Pharrell was a very early Crocs adopter and has worn them in public multiple times. His LV platform gives the brand a luxury-adjacent halo that makes Crocs seem more fashion-forward by cultural proximity.",
    relevanceScore: 82,
    trendStrength: 75,
    tags: ["Louis Vuitton", "streetwear", "luxury fashion", "Pharrell", "early adopter", "fashion credibility"],
    source: "WWD / Vogue / Business of Fashion",
    date: "2026-01-10",
  },
  {
    id: "old-money-aesthetic-teens",
    category: "style",
    type: "trend",
    name: "Old Money Aesthetic Hits Gen Alpha",
    description: "The 'old money' aesthetic — preppy, understated, equestrian — has now trickled all the way down to Gen Alpha. This creates an interesting tension with Crocs' 'new ugly cool' positioning. However, the trend creates a Jibbitz opportunity: classic, heritage-referencing charm sets (plaid, crest, sport) that let Crocs wearers play in this space with their own expressive twist. The preppy Crocs customization niche is growing on TikTok.",
    relevanceScore: 72,
    trendStrength: 68,
    tags: ["old money", "preppy", "Gen Alpha", "Jibbitz opportunity", "customization", "heritage aesthetic"],
    source: "TikTok / Pinterest / Teen Vogue",
    date: "2026-02-08",
  },
  {
    id: "secondhand-resale-boom",
    category: "style",
    type: "trend",
    name: "Secondhand & Resale Boom",
    description: "The secondhand fashion market is now larger than fast fashion for Gen Z. ThredUp, Depop, and Vinted are all posting record metrics. Crocs are among the most-resold comfort shoes on these platforms, indicating strong brand desire and value retention. The resale community also customizes Crocs aggressively (paint, Jibbitz, dye) — this is an organic creative community Crocs could authentically partner with.",
    relevanceScore: 78,
    trendStrength: 82,
    tags: ["resale", "Depop", "sustainability", "Gen Z", "customization", "brand desire", "circular fashion"],
    source: "ThredUp 2025 Resale Report / Depop",
    date: "2026-02-01",
  },
  {
    id: "ballet-flats-comfort-merge",
    category: "style",
    type: "trend",
    name: "Ballet Flat & Comfort Shoe Convergence",
    description: "Ballet flats dominated 2024–25 fashion, but the trend is evolving into a broader 'elegant comfort' category. Brands like Birkenstock and Clarks have benefited enormously. Crocs' new flatter silhouettes (Brooklyn, Getaway) are positioned in this space but haven't captured the fashion editorial moment yet. Stronger styling partnerships and editorial placement in 'elevated comfort' roundups would accelerate this.",
    relevanceScore: 75,
    trendStrength: 71,
    tags: ["ballet flats", "comfort fashion", "Birkenstock", "Brooklyn Clog", "editorial", "elevated comfort"],
    source: "Vogue / Elle / Net-a-Porter",
    date: "2026-01-25",
  },
  {
    id: "color-dopamine-dressing",
    category: "style",
    type: "trend",
    name: "Dopamine Dressing Goes Mainstream",
    description: "Wearing maximally bright, mood-boosting colors as a deliberate emotional strategy has become a widely discussed trend. Gen Z and millennials are increasingly dressing for joy rather than status. Crocs' 50+ colorways are custom-made for this moment — no other footwear brand can match the color breadth. The 'Which Crocs color are you?' content format is organically spreading but hasn't been supercharged with media support yet.",
    relevanceScore: 86,
    trendStrength: 84,
    tags: ["dopamine dressing", "color", "joy", "maximalism", "colorways", "emotional fashion", "campaign idea"],
    source: "Pantone / Pinterest Predicts / Harper's Bazaar",
    date: "2026-02-14",
  },

  {
    id: "coachella-2026",
    category: "style",
    type: "news",
    name: "Coachella 2026 – Festival Fashion Peak",
    description: "Coachella 2026 (April) is weeks away and festival fashion content is already peaking on social media. Crocs are organically one of the most-worn footwear choices at Coachella — comfortable for all-day standing, expressive with Jibbitz, and increasingly styled with festival outfits. This is a real-time activation window: seeding product with festival influencers, creating a Coachella-themed Jibbitz pack, or sponsoring a stage activation would capture massive organic attention.",
    relevanceScore: 88,
    trendStrength: 93,
    tags: ["Coachella", "festival fashion", "April 2026", "influencer seeding", "Jibbitz", "organic usage", "real-time"],
    source: "Instagram / TikTok / Rolling Stone",
    date: "2026-03-10",
  },

  // ─── ENTERTAINMENT ────────────────────────────────────────────────────────

  {
    id: "taylor-swift-new-era",
    category: "entertainment",
    type: "celebrity",
    name: "Taylor Swift – New Era, Same Cultural Gravity",
    description: "Post-Eras Tour, Taylor is in a creative reset phase — and Swifties are at peak hunger for anything new. This is historically her most commercially powerful moment: the anticipation era. Her fan community remains the most commercially influential fandom in the world. Crocs' organic Swiftie adoption (custom Jibbitz packs, Eras-themed styling content) has been building quietly — a formal collaboration announcement during this anticipation window would be an industry-defining moment.",
    relevanceScore: 94,
    trendStrength: 86,
    tags: ["Taylor Swift", "Swifties", "new era", "fandom", "Jibbitz DIY", "celebrity collab", "cultural institution"],
    source: "Billboard / TikTok / People",
    date: "2026-03-08",
  },
  {
    id: "beyonce-brand-empire",
    category: "entertainment",
    type: "celebrity",
    name: "Beyoncé – Brand Empire Expansion",
    description: "Post-Cowboy Carter tour, Beyoncé is in full brand-building mode — her Cécred haircare line is scaling rapidly and her broader lifestyle brand ambitions are well documented. She's building a consumer goods empire while maintaining her status as the most culturally resonant female artist alive. Her audience (25–45, high income, style-conscious) is an aspirational segment Crocs has not fully captured. A premium Beyoncé x Crocs limited edition would be the brand's highest-profile collab to date.",
    relevanceScore: 87,
    trendStrength: 80,
    tags: ["Beyoncé", "brand empire", "Cécred", "lifestyle brand", "premium collab", "aspirational segment"],
    source: "Business of Fashion / Forbes / Billboard",
    date: "2026-03-01",
  },
  {
    id: "pedro-pascal-beloved",
    category: "entertainment",
    type: "celebrity",
    name: "Pedro Pascal – Internet's Comfort Character",
    description: "Pascal has spent the past two years cementing himself as the internet's beloved 'dad character' — warm, self-deprecating, and endlessly meme-able. The Last of Us Season 3 is in production, keeping his profile elevated. His fan community organizes regular charity events and is known for buying large quantities of branded merchandise from actors they love. His aesthetic (casual, dark-cool) doesn't directly map to Crocs, but his personality absolutely does.",
    relevanceScore: 80,
    trendStrength: 76,
    tags: ["Pedro Pascal", "internet darling", "The Last of Us", "fandom", "merch culture", "warm brand personality"],
    source: "HBO / Rolling Stone / X Fan Communities",
    date: "2026-02-02",
  },
  {
    id: "sydney-sweeney-americana",
    category: "entertainment",
    type: "celebrity",
    name: "Sydney Sweeney – Americana Nostalgia Icon",
    description: "Sweeney has positioned herself as the face of 2026's 'soft americana' aesthetic — blonde, retro-glamour, unapologetically feminine, with a sharp comedic sensibility (her Anyone But You and SNL hosting moments). Her fan base skews 18–30, female, and is among the most engaged on Instagram and TikTok. She's partnered with American Eagle, Ford, and Laneige — all comfort/authenticity plays. A Crocs partnership conversation is timely.",
    relevanceScore: 84,
    trendStrength: 80,
    tags: ["Sydney Sweeney", "americana", "feminine", "Gen Z women", "retro", "comedy", "brand fit"],
    source: "People / Vogue / Box Office Mojo",
    date: "2026-02-10",
  },
  {
    id: "wicked-cultural-impact",
    category: "entertainment",
    type: "news",
    name: "Wicked Film – Pink Wave Aftermath",
    description: "The Wicked film (Nov 2024) generated a year-long cultural pink-and-green wave that is still active in early 2026. The pink/green color pairing — identical to Crocs' brand palette potential — was plastered everywhere. Crocs released a limited Elphaba/Glinda collaboration that sold out in 2 hours. The sequel (Wicked: Part 2) releases Nov 2026, creating a second wave opportunity with significantly more lead time for Crocs to plan a major activation.",
    relevanceScore: 88,
    trendStrength: 79,
    tags: ["Wicked", "pink", "green", "Broadway", "film collab", "sequel opportunity", "color moment", "sell-out"],
    source: "Universal Pictures / Box Office Mojo / Crocs PR",
    date: "2026-01-08",
  },
  {
    id: "booktok-community",
    category: "entertainment",
    type: "trend",
    name: "BookTok – Comfort Creator Economy",
    description: "BookTok has 45B+ views and has turned reading into a social identity for Gen Z. The BookTok aesthetic — cozy reading nooks, blanket hoodies, hot beverages, comfort footwear — is Crocs territory. Several popular BookTok creators have organically featured Crocs in 'my reading setup' content. A BookTok creator partnership focused on 'ultimate comfort reading experience' is low-cost, high-authenticity, and directly on-brand.",
    relevanceScore: 81,
    trendStrength: 83,
    tags: ["BookTok", "creator economy", "comfort aesthetic", "cozy", "Gen Z women", "organic", "influencer"],
    source: "TikTok / Publishers Weekly",
    date: "2026-01-25",
  },
  {
    id: "live-events-boom",
    category: "entertainment",
    type: "trend",
    name: "Live Events Renaissance",
    description: "Post-pandemic, consumers are consistently prioritizing live experiences over things. Concert, sports, and festival spending is at all-time highs. Crocs is already the de facto footwear for music festival attendees (comfortable for all-day standing, easy to clean, expressive with Jibbitz). There's a massive opportunity to own the 'festival footwear' positioning with dedicated campaigns, artist partnerships, and festival activations at Coachella, Lollapalooza, and Glastonbury.",
    relevanceScore: 87,
    trendStrength: 88,
    tags: ["live events", "festivals", "Coachella", "concert", "experiential", "festival footwear", "organic usage"],
    source: "Pollstar / Live Nation / Eventbrite",
    date: "2026-02-03",
  },
  {
    id: "reality-tv-renaissance",
    category: "entertainment",
    type: "trend",
    name: "Reality TV Renaissance",
    description: "Reality TV is having its biggest cultural moment since the early 2000s. Love Island USA, Traitors US, and The Bachelor franchise are driving massive social conversation. Reality TV cast members are becoming micro-celebrities with dedicated fan bases almost overnight. The cast of Traitors S3 generated over $8M in combined endorsement deals within 60 days of the season ending. Crocs can authentically play here — contestants wearing Crocs in house/villa settings is highly plausible and trendable.",
    relevanceScore: 79,
    trendStrength: 81,
    tags: ["reality TV", "Traitors", "Love Island", "micro-celebrity", "fast deals", "endorsement", "organic placement"],
    source: "Peacock / CBS / Nielsen",
    date: "2026-01-28",
  },
  {
    id: "sabrina-carpenter-entertainment",
    category: "entertainment",
    type: "celebrity",
    name: "Sabrina Carpenter – Pop Moment of the Decade",
    description: "Carpenter's Short n' Sweet era put her in the conversation as the biggest pop star of the moment. Her 2026 world tour is already sold out across all dates. She's broken streaming records and her wit and humor make her uniquely endearing across demographics. Her brand deals (Laneige, espresso brand partnerships) show she gravitates toward fun, personality-forward brands. A Crocs conversation is a natural next step — she's been photographed in comfort footwear repeatedly.",
    relevanceScore: 93,
    trendStrength: 91,
    tags: ["Sabrina Carpenter", "pop music", "tour", "humor", "Gen Z", "brand deals", "photographed in comfort shoes"],
    source: "Billboard / Spotify / People",
    date: "2026-02-20",
  },
  {
    id: "chappell-roan-community",
    category: "entertainment",
    type: "celebrity",
    name: "Chappell Roan – Queer Maximalism Icon",
    description: "Roan's debut year was one of the most remarkable in pop history. Her unapologetically maximalist, drag-inspired visual aesthetic and fierce advocacy for LGBTQ+ audiences is a rare combination of commercial success and cultural authenticity. Her fan community is passionately creative — costume builds, art, DIY merchandise. The 'Good Luck Babe' and 'Pink Pony Club' aesthetics map directly to Crocs' boldest colorways and the Jibbitz customization community. A Chappell Roan Crocs collab would be a lightning rod moment.",
    relevanceScore: 89,
    trendStrength: 85,
    tags: ["Chappell Roan", "LGBTQ+", "maximalism", "drag aesthetic", "DIY culture", "authentic", "bold colors", "Jibbitz"],
    source: "Billboard / Pitchfork / GLAAD",
    date: "2026-02-08",
  },
  {
    id: "oscars-2026",
    category: "entertainment",
    type: "news",
    name: "Awards Season 2026 – Style Conversations",
    description: "The 2026 Oscars and awards season are generating massive style conversation right now. Red carpet fashion is one of the highest-engagement content categories of the year. The emerging 'awards season comfort' trend — celebrities photographed in cozy, expressive footwear backstage and in candid moments — is an owned social niche Crocs can lean into. Seeding product to stylists and talent walking this season could yield highly shareable organic moments.",
    relevanceScore: 78,
    trendStrength: 88,
    tags: ["Oscars", "awards season", "red carpet", "celebrity seeding", "backstage fashion", "stylists", "organic moment"],
    source: "Vogue / WWD / People",
    date: "2026-03-05",
  },
  {
    id: "wicked-part-2",
    category: "entertainment",
    type: "news",
    name: "Wicked: Part 2 – November 2026 Activation Window",
    description: "Wicked: For Good (Part 2) releases November 2026, and pre-release buzz is already building. The first Crocs x Wicked collab sold out in 2 hours. With 8 months of lead time, Crocs can plan a significantly larger activation — expanded SKU range, dedicated marketing campaign, and global launch coordination. The pink/green aesthetic is owned Crocs territory. This is the single highest-priority licensed collab opportunity in the next 12 months.",
    relevanceScore: 91,
    trendStrength: 85,
    tags: ["Wicked Part 2", "November 2026", "licensed collab", "pink green", "sell-out risk", "sequel", "global launch"],
    source: "Universal Pictures / Deadline / Crocs PR",
    date: "2026-03-08",
  },
  {
    id: "asmr-comfort-content",
    category: "entertainment",
    type: "trend",
    name: "Comfort Content & ASMR Economy",
    description: "The 'comfort content' category — ASMR, slow living, cozy gaming, lo-fi study streams — continues to grow as Gen Z seeks calm in a chaotic media environment. YouTube channels dedicated to comfort content average 8–15 million weekly views. Crocs fits organically into this aesthetic: unboxing Crocs, the satisfying click of Jibbitz, barefoot comfort sounds. Investing in creator partnerships within this space would be low-cost and culturally resonant.",
    relevanceScore: 76,
    trendStrength: 78,
    tags: ["ASMR", "comfort content", "YouTube", "slow living", "Gen Z wellness", "creator economy", "unboxing"],
    source: "YouTube / Creator IQ / Tubular Labs",
    date: "2026-01-18",
  },
];

// Category metadata for summary cards
const AFFINITY_CATEGORIES = [
  {
    id: "sport",
    label: "Sport",
    color: "#3b82f6",
    colorLight: "#eff6ff",
    colorBorder: "#bfdbfe",
    icon: "🏆",
    description: "Athletes, leagues, and sports culture moments relevant to Crocs partnerships and campaign alignment.",
  },
  {
    id: "style",
    label: "Style",
    color: "#8b5cf6",
    colorLight: "#f5f3ff",
    colorBorder: "#ddd6fe",
    icon: "✨",
    description: "Fashion trends, cultural style movements, and celebrities shaping the aesthetic context Crocs operates in.",
  },
  {
    id: "entertainment",
    label: "Entertainment",
    color: "#ec4899",
    colorLight: "#fdf2f8",
    colorBorder: "#fbcfe8",
    icon: "🎬",
    description: "Music, film, TV, and digital entertainment figures and trends driving cultural conversation.",
  },
];

const AFFINITY_TYPES = [
  { id: "celebrity", label: "Celebrity" },
  { id: "campaign", label: "Campaign" },
  { id: "trend", label: "Trend" },
  { id: "news", label: "News" },
];
