// Sustainability Marketing Dashboard - Data Layer
// In production, replace with API calls to data aggregators / social listening tools

const BRANDS = {
  crocs: {
    name: "Crocs",
    isSelf: true,
    overallScore: 72,
    campaignVolume: 34,
    sentiment: "positive",
    sentimentScore: 74,
    trend: "up",
    pillars: ["Bio-Based Materials", "Circularity", "Carbon Reduction"],
    recentInitiative: "Bio-based Croslite expansion - targeting 50% bio-content by 2027",
    monthlyVolume: [12, 14, 16, 18, 20, 22, 25, 24, 28, 30, 32, 34],
  },
  nike: {
    name: "Nike",
    overallScore: 91,
    campaignVolume: 82,
    sentiment: "positive",
    sentimentScore: 81,
    trend: "up",
    pillars: ["Circularity", "Renewable Energy", "Water Stewardship", "Community"],
    recentInitiative: "Nike Refurbished program expansion to 300+ stores globally",
    monthlyVolume: [55, 58, 60, 63, 65, 68, 70, 72, 75, 78, 80, 82],
  },
  adidas: {
    name: "Adidas",
    overallScore: 88,
    campaignVolume: 76,
    sentiment: "positive",
    sentimentScore: 79,
    trend: "up",
    pillars: ["Ocean Plastic", "Circularity", "Carbon Neutrality", "Sustainable Cotton"],
    recentInitiative: "Made to Be Remade 3.0 - fully circular performance line",
    monthlyVolume: [50, 52, 55, 58, 60, 63, 65, 68, 70, 72, 74, 76],
  },
  birkenstock: {
    name: "Birkenstock",
    overallScore: 82,
    campaignVolume: 38,
    sentiment: "positive",
    sentimentScore: 85,
    trend: "up",
    pillars: ["Natural Materials", "Longevity", "Repair Programs", "Responsible Sourcing"],
    recentInitiative: "Lifetime repair guarantee and cork recycling take-back program",
    monthlyVolume: [20, 22, 24, 25, 27, 28, 30, 32, 33, 35, 36, 38],
  },
  skechers: {
    name: "Skechers",
    overallScore: 54,
    campaignVolume: 18,
    sentiment: "neutral",
    sentimentScore: 58,
    trend: "flat",
    pillars: ["Recycled Materials", "Energy Efficiency"],
    recentInitiative: "Recycled polyester integration in Arch Fit line",
    monthlyVolume: [10, 11, 12, 13, 13, 14, 15, 15, 16, 17, 17, 18],
  },
  newBalance: {
    name: "New Balance",
    overallScore: 68,
    campaignVolume: 30,
    sentiment: "positive",
    sentimentScore: 71,
    trend: "up",
    pillars: ["Domestic Manufacturing", "Green Leather", "Renewable Energy"],
    recentInitiative: "Green Leaf Standard 3.0 - plant-based performance materials",
    monthlyVolume: [15, 17, 18, 20, 21, 23, 24, 25, 27, 28, 29, 30],
  },
  puma: {
    name: "Puma",
    overallScore: 76,
    campaignVolume: 45,
    sentiment: "positive",
    sentimentScore: 72,
    trend: "up",
    pillars: ["Biodiversity", "Fair Wages", "Circularity", "Climate Targets"],
    recentInitiative: "RE:SUEDE 2.0 - biodegradable sneaker with industrial composting",
    monthlyVolume: [28, 30, 32, 34, 35, 37, 38, 39, 41, 42, 44, 45],
  },
  vans: {
    name: "Vans",
    overallScore: 51,
    campaignVolume: 15,
    sentiment: "neutral",
    sentimentScore: 55,
    trend: "flat",
    pillars: ["Organic Materials", "Packaging Reduction"],
    recentInitiative: "Eco Theory collection with organic canvas and natural dyes",
    monthlyVolume: [8, 9, 9, 10, 10, 11, 12, 12, 13, 13, 14, 15],
  },
  allbirds: {
    name: "Allbirds",
    overallScore: 95,
    campaignVolume: 68,
    sentiment: "positive",
    sentimentScore: 88,
    trend: "up",
    pillars: ["Carbon Labeling", "Regenerative Ag", "Bio-Based Materials", "Transparency"],
    recentInitiative: "Carbon footprint labeling on all products with real-time LCA data",
    monthlyVolume: [45, 48, 50, 52, 55, 57, 58, 60, 62, 64, 66, 68],
  },
  hoka: {
    name: "Hoka",
    overallScore: 60,
    campaignVolume: 22,
    sentiment: "neutral",
    sentimentScore: 63,
    trend: "up",
    pillars: ["Recycled Materials", "Sustainable Packaging", "Carbon Offsets"],
    recentInitiative: "Recycled EVA midsole program piloted across trail running line",
    monthlyVolume: [10, 11, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
  },
};

const EMERGING_THEMES = [
  { label: "Carbon Labeling", weight: 92, color: "#2e8b57" },
  { label: "Regenerative Agriculture", weight: 85, color: "#3b82f6" },
  { label: "Biodegradable Materials", weight: 81, color: "#8b5cf6" },
  { label: "Circular Take-Back", weight: 78, color: "#f59e0b" },
  { label: "Supply Chain Transparency", weight: 76, color: "#ef4444" },
  { label: "Water Stewardship", weight: 70, color: "#06b6d4" },
  { label: "Bio-Based Polymers", weight: 68, color: "#10b981" },
  { label: "Living Wages", weight: 64, color: "#ec4899" },
  { label: "Microplastic Reduction", weight: 61, color: "#6366f1" },
  { label: "Repair & Longevity", weight: 58, color: "#84cc16" },
  { label: "Nature-Positive Targets", weight: 55, color: "#14b8a6" },
  { label: "Digital Product Passports", weight: 50, color: "#a855f7" },
];

const RECENT_CAMPAIGNS = [
  {
    brand: "Nike",
    title: "Move to Zero: Season 5",
    description: "Expanded circular design principles across 80% of product lines with consumer-facing sustainability scores.",
    date: "2026-02-28",
    channel: "Multi-channel",
    engagement: "Very High",
  },
  {
    brand: "Adidas",
    title: "Made to Be Remade 3.0",
    description: "Third generation of fully circular products with QR-code return system and material credit rewards.",
    date: "2026-02-20",
    channel: "Digital + Retail",
    engagement: "High",
  },
  {
    brand: "Allbirds",
    title: "Flight Status: Carbon Dashboard",
    description: "Real-time public carbon dashboard showing per-product lifecycle emissions with industry benchmarking.",
    date: "2026-03-01",
    channel: "Digital",
    engagement: "Very High",
  },
  {
    brand: "Puma",
    title: "RE:SUEDE Composting Results",
    description: "Published 18-month composting trial results showing 90% biodegradation. Expanding to mainline products.",
    date: "2026-02-15",
    channel: "PR + Social",
    engagement: "High",
  },
  {
    brand: "Birkenstock",
    title: "Forever Birkenstock Repair Hub",
    description: "Launched 50 in-store repair stations and mail-in resoling service with lifetime repair guarantee.",
    date: "2026-02-10",
    channel: "Retail + Digital",
    engagement: "High",
  },
  {
    brand: "New Balance",
    title: "Green Leaf Standard 3.0",
    description: "Introduced plant-based performance materials across running line with third-party sustainability certification.",
    date: "2026-01-30",
    channel: "PR + Digital",
    engagement: "Medium",
  },
  {
    brand: "Crocs",
    title: "Bio-Croslite Progress Report",
    description: "Published Q4 progress on bio-based Croslite adoption: 35% bio-content achieved across Classic line.",
    date: "2026-02-22",
    channel: "Corporate + Social",
    engagement: "Medium",
  },
  {
    brand: "Hoka",
    title: "Trail to Trail Recycling",
    description: "Launched shoe collection bins at 200 trailheads partnering with national parks for recycled EVA recovery.",
    date: "2026-01-25",
    channel: "Experiential",
    engagement: "Medium",
  },
];

// Pillar categories for radar/gap analysis
const GAP_DIMENSIONS = [
  "Carbon Transparency",
  "Circular Programs",
  "Bio-Based Materials",
  "Supply Chain Ethics",
  "Consumer Education",
  "Third-Party Certs",
];

const GAP_DATA = {
  crocs:       [55, 50, 75, 60, 45, 50],
  peerAverage: [78, 72, 65, 70, 68, 74],
  leader:      [95, 90, 88, 85, 90, 92],
};
