// Jibbitz Trends - Data Layer
// Sources: Google Trends RSS, NPR Pop Culture, Variety, Billboard, Hypebeast, BuzzFeed Trending, TMZ

const JIBBITZ_LAST_UPDATED = "2026-04-29";

// ─── DATA NOTICE ────────────────────────────────────────────────────────────
// confidence: "verified"  = real cultural event, sourced from named press coverage
//             "modeled"   = AI-generated placeholder, NOT a real event — remove before sharing externally
// momentum: editorial assessment of current trend trajectory — "surging" | "rising" | "steady" | "fading" | "peaked"
// jibbitzScore: editorial 0-100 rating of commercial charm potential — not a pulled metric
// searchTrend: relative interest curve (0-100), directional only, not API-sourced
// source field: lists the outlets where this trend was confirmed — fetched on last updated date above

const JIBBITZ_TRENDS = [
  {
    id: "nihilist-penguin",
    name: "Nihilist Penguin",
    category: "memes",
    confidence: "verified",
    confidenceNote: "Real clip — from Werner Herzog's 2007 documentary 'Encounters at the End of the World'. Went viral Jan 16, 2026 via TikTok (@natur_gamler), 1.5M+ likes in 5 days. Used by BMW, Lidl and others.",
    description: "A lone Adélie penguin breaking from its colony and walking toward a distant mountain — alone, unbothered, done with it all. Gen Z's emotional support meme for burnout, quiet quitting, and anti-conformity. The penguin silhouette walking into the distance is a perfect charm.",
    source: "TikTok / X / Instagram",
    daysTrending: 21,
    momentum: "steady",
    jibbitzScore: 91,
    stage: "evaluation",
    stageDetail: "Strong candidate — the 'walking away' silhouette is iconic and Jibbitz-scale friendly. Brands already using this signal",
    searchTrend: [0, 0, 2, 8, 35, 72, 95, 100, 92, 85, 80, 78, 75, 74],
    regional: { US: 0, JP: 0, CN: 0, KR: 0, IN: 0, UK: 0, FR: 0, DE: 0 },
    audience: { "Gen Z": 96, "Millennials": 80, "Parents": 45, "Kids": 20 },
  },
  {
    id: "calamity-cat",
    name: "Calamity Cat",
    category: "memes",
    confidence: "verified",
    confidenceNote: "Real meme — ginger cat with bread slice on its head. Dormant since 2023, re-exploded Feb 2026 on X after viral 'autocorrect to boss' post. Confirmed by Know Your Meme and cheezburger coverage.",
    description: "Wide-eyed ginger cat with a slice of bread on its head — the universal face of 'a small problem that just became your whole personality'. Went viral again Feb 2026 and became Gen Z's go-to reaction image for chaos escalation. Simple, static, wildly remixable.",
    source: "X / TikTok / Reddit",
    daysTrending: 105,
    momentum: "rising",
    jibbitzScore: 85,
    stage: "evaluation",
    stageDetail: "Strong visual — cat face + bread slice reads instantly at charm scale. No licensing needed, the original photo is meme-culture commons",
    searchTrend: [0, 2, 8, 25, 55, 78, 88, 92, 90, 87, 84, 82, 80, 79],
    regional: { US: 0, JP: 0, CN: 0, KR: 0, IN: 0, UK: 0, FR: 0, DE: 0 },
    audience: { "Gen Z": 95, "Millennials": 82, "Parents": 40, "Kids": 35 },
  },
  {
    id: "boy-kibble",
    name: "Boy Kibble",
    category: "food",
    confidence: "verified",
    confidenceNote: "Real trend — ground beef + rice high-protein bowl coined by fitness creator 'Quadfather' (Christian Miles) Jan 2026. Covered by Fortune, Fox News, Healthline, The Tab. Went mainstream Feb-Mar 2026.",
    description: "Gen Z men eating plain ground beef and rice up to 7x a week for cheap protein. Dubbed 'boy kibble' because it looks like dog food. The internet is obsessed — half horrified, half inspired. A beef bowl Jibbitz would be peak irony charm energy.",
    source: "TikTok / Fortune / Fox News / Healthline",
    daysTrending: 28,
    momentum: "rising",
    jibbitzScore: 82,
    stage: "evaluation",
    stageDetail: "No licensing needed — beef bowl / rice bowl charm concept is completely original. The irony factor drives sharing",
    searchTrend: [0, 2, 5, 15, 35, 58, 72, 82, 88, 90, 88, 85, 84, 83],
    regional: { US: 0, JP: 0, CN: 0, KR: 0, IN: 0, UK: 0, FR: 0, DE: 0 },
    audience: { "Gen Z": 90, "Millennials": 72, "Parents": 35, "Kids": 20 },
  },
  {
    id: "coachella-caviar-fries",
    name: "Coachella $28 Fries",
    category: "food",
    confidence: "verified",
    confidenceNote: "Real event — Coachella 2026 food prices went massively viral April 10-13. $17 lattes, $28 fries, $150 caviar-topped burger documented and shared across X, TikTok, and Reddit. Covered by Digital Music News, The Mirror, The Kitchn, Yahoo Lifestyle. Weekend 1 ran April 10-12, Weekend 2 April 17-19. Both over.",
    description: "Coachella 2026 food prices broke the internet — $17 lattes, $28 plain fries, a $150 burger finished with caviar. Festivalgoers posting receipts and price tags became the dominant content from weekend one, beating out the actual performances for engagement. The charm concept is the gag: a tiny paper cup of fries with a single pearl of caviar resting on top. Luxury absurdism, no licensing, very Crocs.",
    source: "X / TikTok / Digital Music News / The Mirror / Yahoo Lifestyle",
    daysTrending: 19,
    momentum: "peaked",
    jibbitzScore: 87,
    stage: "evaluation",
    stageDetail: "Festival is over — both weekends done. Window has closed. File for future festival season activation.",
    searchTrend: [0, 0, 0, 0, 45, 82, 96, 100, 98, 78, 52, 32, 18, 10],
    regional: { US: 96, JP: 55, CN: 50, KR: 60, IN: 45, UK: 80, FR: 82, DE: 75 },
    audience: { "Gen Z": 94, "Millennials": 90, "Parents": 48, "Kids": 20 },
  },
  {
    id: "bieber-watches-youtube",
    name: "Bieber Watches YouTube",
    category: "memes",
    confidence: "verified",
    confidenceNote: "Real event — Justin Bieber performed at Coachella April 11, 2026, then sat at a laptop and browsed YouTube for the audience. Video went viral immediately. Know Your Meme entry created April 12. Green screen edits spread across X and TikTok. Covered by Complex, Curly Tales, ClutchPoints.",
    description: "Justin Bieber headlined Coachella, played some songs, then sat down in front of a laptop and watched YouTube in front of 100,000 people. The internet lost it. A green screen of the moment launched a template meme where everyone edits in different content on the laptop screen. The charm concept doesn't need his likeness — a tiny open laptop with a play button on the screen is the joke.",
    source: "X / TikTok / Know Your Meme / Complex / ClutchPoints",
    daysTrending: 18,
    momentum: "peaked",
    jibbitzScore: 84,
    stage: "evaluation",
    stageDetail: "Coachella is over, meme cycle complete. Window closed — this needed to move within 10 days of April 11.",
    searchTrend: [0, 0, 0, 0, 0, 20, 75, 98, 100, 82, 58, 35, 20, 10],
    regional: { US: 95, JP: 60, CN: 50, KR: 65, IN: 58, UK: 88, FR: 80, DE: 82 },
    audience: { "Gen Z": 96, "Millennials": 90, "Parents": 40, "Kids": 38 },
  },
  {
    id: "kitkat-heist",
    name: "The Great KitKat Heist",
    category: "memes",
    confidence: "verified",
    confidenceNote: "Real event — 12 tons (413,793 bars) of KitKat stolen from a truck traveling Italy to Poland, March 29, 2026. KitKat's official X statement received 132M+ views. Brands including DoorDash, KFC, and Domino's posted fake confession statements. KitKat launched a live 'stolen tracker' on April 1. Covered by Time, USA Today, Newsweek, Khaleej Times.",
    description: "Over 400,000 KitKat bars vanished from a European transport truck and the internet immediately turned it into the chocolatiest crime of the century. Every brand on X posted a fake confession. KitKat launched a 'stolen bar tracker' where you enter your batch number to find out if your chocolate is hot goods. The charm: a generic chocolate bar wearing a tiny ski mask — no KitKat licensing needed, just vibes.",
    source: "X / Time / USA Today / Newsweek / Know Your Meme",
    daysTrending: 91,
    momentum: "fading",
    jibbitzScore: 89,
    stage: "evaluation",
    stageDetail: "Trending for a month — conversation fading. Chocolate bar in a balaclava is a timeless enough concept to greenlight even past peak. Last call.",
    searchTrend: [0, 0, 0, 0, 5, 55, 95, 100, 92, 72, 55, 42, 32, 25],
    regional: { US: 5, JP: 0, CN: 0, KR: 2, IN: 3, UK: 14, FR: 0, DE: 1 },
    audience: { "Gen Z": 92, "Millennials": 88, "Parents": 62, "Kids": 55 },
  },
  {
    id: "erewhon-strawberry",
    name: "$20 Strawberry",
    category: "food",
    confidence: "verified",
    confidenceNote: "Real product — single Japanese Tochiaika strawberry from Kyoto sold at Erewhon LA for $19-20, packaged on a velvet cushion inside a miniature plastic cloche. Viral TikTok by Alyssa Antoci garnered 17M+ views. Covered by The Guardian, Food & Wine, Today, ABC News. February 2026.",
    description: "A single strawberry. Imported from Kyoto. Packaged on a velvet cushion inside its own tiny glass dome. $20. The reactions ranged from 'dystopian' to 'best thing I've ever eaten' — and that gap is exactly where internet gold lives. The charm concept writes itself: a tiny strawberry sitting in a miniature glass cloche on a velvet cushion. No licensing, just one extremely precious piece of fruit.",
    source: "TikTok / The Guardian / Food & Wine / Today / ABC News",
    daysTrending: 140,
    momentum: "rising",
    jibbitzScore: 86,
    stage: "evaluation",
    stageDetail: "No licensing required — a strawberry in a glass dome is a generic luxury-absurdism concept. The discourse is still live. A 'very fancy strawberry' charm is the kind of unexpected move that generates earned media coverage by itself.",
    searchTrend: [0, 0, 2, 8, 25, 55, 80, 92, 96, 100, 95, 90, 87, 85],
    regional: { US: 100, JP: 0, CN: 0, KR: 0, IN: 0, UK: 0, FR: 0, DE: 0 },
    audience: { "Gen Z": 90, "Millennials": 92, "Parents": 50, "Kids": 30 },
  },
  {
    id: "punch-monkey",
    name: "Punch the Monkey",
    category: "animals",
    confidence: "verified",
    confidenceNote: "Real event — Zoo Atlanta, Jan 2026. Crocs launched a Jibbitz on Mar 1.",
    description: "Baby spider monkey at Zoo Atlanta who went viral for clutching his stuffed animal. 200M+ views across platforms. Pure joy content.",
    source: "TikTok / Instagram",
    daysTrending: 59,
    momentum: "fading",
    jibbitzScore: 99,
    stage: "launched",
    stageDetail: "Launched Mar 1 — best-performing social post ever, massive PR pickup. Now in long tail.",
    searchTrend: [5, 15, 40, 78, 95, 100, 92, 80, 65, 50, 38, 28, 20, 15],
    regional: { US: 0, JP: 0, CN: 0, KR: 0, IN: 0, UK: 0, FR: 0, DE: 0 },
    audience: { "Gen Z": 90, "Millennials": 85, "Parents": 88, "Kids": 82 },
  },
  {
    id: "wabi-sabi",
    name: "Wabi-Sabi",
    category: "memes",
    confidence: "verified",
    confidenceNote: "Real viral TikTok trend — sound pulled from King of the Hill (Bobby Hill: 'I like how mine's a little off-centre — it's got wabi-sabi') has generated ~500K videos on TikTok. Covered by Fast Company, CBC Kids News, The Tab, Know Your Meme, Twisted Sifter (Jan 2026).",
    description: "TikTok is celebrating imperfection using a King of the Hill audio clip. Bobby Hill's deadpan 'it's got wabi-sabi' has become the Gen Z anthem for embracing the crooked, chipped, mismatched, and off-centre. The brand alignment is almost uncomfortably perfect — Crocs is the original wabi-sabi shoe. A tiny cracked ceramic tea bowl (the classic wabi-sabi object) is the charm concept, but Crocs itself IS the message.",
    source: "TikTok / Fast Company / Know Your Meme / The Tab",
    daysTrending: 14,
    momentum: "rising",
    jibbitzScore: 88,
    stage: "evaluation",
    stageDetail: "Zero licensing risk — wabi-sabi is a 400-year-old Japanese philosophy, not IP. The King of the Hill audio is the vehicle but the charm concept doesn't need it. Act while the sound is still in active rotation.",
    searchTrend: [0, 2, 5, 12, 28, 52, 72, 85, 92, 96, 100, 98, 94, 90],
    regional: { US: 0, JP: 0, CN: 0, KR: 0, IN: 0, UK: 0, FR: 0, DE: 0 },
    audience: { "Gen Z": 94, "Millennials": 80, "Parents": 42, "Kids": 30 },
  },
  {
    id: "purple-ube",
    name: "Purple Ube",
    category: "food",
    confidence: "verified",
    confidenceNote: "Real mainstream food trend — 120K TikTok posts, 750K+ Instagram posts. Starbucks added Ube Matcha Latte and Ube Vanilla Macchiato to 2026 spring lineup. Menu presence up 230% across US chains per Datassential. CNBC, Food Navigator, Cosmopolitan India, The Food Institute all covered April 2026. Filipino purple yam going global.",
    description: "Ube — the Filipino purple yam with earthy vanilla-coconut flavour — is having its matcha moment. Starbucks, Dunkin', and 95 US chains now serve it. The colour is the hook: an impossible electric purple that photographs like nothing else on the internet. The charm is obvious — a smooth purple yam root or a tiny ube latte with swirling purple foam. Celebration of Filipino culture going global is the earned media angle.",
    source: "CNBC / Food Navigator / Starbucks / Datassential / TikTok",
    daysTrending: 14,
    momentum: "surging",
    jibbitzScore: 85,
    stage: "evaluation",
    stageDetail: "No licensing required — ube is a food ingredient, not IP. Strong APAC relevance (PH, KR, JP) alongside US mainstream moment. Window: 60-90 days before oversaturation. Could pair with Filipino Heritage Month (October).",
    searchTrend: [0, 2, 5, 10, 22, 42, 60, 74, 84, 92, 98, 100, 98, 95],
    regional: { US: 0, JP: 0, CN: 0, KR: 0, IN: 0, UK: 0, FR: 0, DE: 0 },
    audience: { "Gen Z": 90, "Millennials": 88, "Parents": 55, "Kids": 45 },
  },
  {
    id: "devil-wears-prada-2",
    name: "The Devil Wears Prada 2",
    category: "fashion",
    confidence: "verified",
    confidenceNote: "Real production — sequel confirmed and actively filming. Original cast returning: Meryl Streep, Anne Hathaway, Emily Blunt, Stanley Tucci. Director David Frankel back. Anna Wintour (the real Miranda Priestly) appeared on Vogue's May 2026 cover alongside Meryl Streep with the tagline 'When Miranda met Anna...' Projected $175–190M global opening weekend. Budget ~$100M. Covered by Variety.",
    description: "The sequel to one of fashion's most quotable films is filming now, and Anna Wintour just posed with Meryl Streep for Vogue's May cover. The original is still a 'cultural touchstone' two decades on — this sequel is reigniting every fashion-obsessed corner of the internet. The charm concept doesn't need character rights: a tiny cerulean blue swatch card, a runway magazine, or a stiletto heel says everything without a single logo. Pure fashion-irony energy.",
    source: "Variety / Vogue",
    daysTrending: 385,
    momentum: "surging",
    jibbitzScore: 88,
    stage: "evaluation",
    stageDetail: "No character licensing needed — fashion-adjacent concepts (cerulean swatch, stiletto, magazine) are generic. The Wintour/Streep Vogue moment is happening now. Window: move before the film releases and conversation peaks.",
    searchTrend: [0, 0, 2, 5, 10, 20, 38, 55, 72, 85, 92, 96, 100, 98],
    regional: { US: 69, JP: 1, CN: 0, KR: 7, IN: 8, UK: 75, FR: 7, DE: 11 },
    audience: { "Gen Z": 85, "Millennials": 96, "Parents": 68, "Kids": 20 },
  },
  {
    id: "michael-jackson-biopic",
    name: "'Michael' Biopic",
    category: "pop-culture",
    confidence: "verified",
    confidenceNote: "Real film — 'Michael', directed by Antoine Fuqua, starring Jaafar Jackson (MJ's nephew). Now in release. NPR reviewed it noting the film covers his rise to stardom while omitting controversial aspects. Variety review: 'The thrill isn't gone... Jaafar Jackson nails his mix of delicacy and steel.' Covered by NPR, Variety.",
    description: "Antoine Fuqua's MJ biopic has Jaafar Jackson channelling his uncle with enough electricity to reopen the debate about the king of pop all over again. The film focuses on the rise — Thriller era, moonwalk, Pepsi commercial — which means the whole internet is rewatching iconic MJ footage and fighting about his legacy in the comments. The charm challenge is real: sequined glove and fedora are iconic, but MJ Estate licensing is the barrier. An original 'moonwalk shoe' silhouette without explicit branding could thread the needle.",
    source: "NPR / Variety",
    daysTrending: 224,
    momentum: "rising",
    jibbitzScore: 78,
    stage: "watching",
    stageDetail: "Licensing from the MJ Estate is the key blocker — evaluate whether an unbranded moonwalk-shoe or sequined-glove silhouette clears legal. If yes, this is a high-ceiling moment while the film is in theaters.",
    searchTrend: [0, 0, 5, 15, 35, 58, 75, 88, 95, 100, 98, 94, 90, 87],
    regional: { US: 53, JP: 3, CN: 0, KR: 17, IN: 57, UK: 55, FR: 100, DE: 15 },
    audience: { "Gen Z": 82, "Millennials": 95, "Parents": 85, "Kids": 45 },
  },
  {
    id: "mob-wife-revival",
    name: "Mob Wife Revival",
    category: "fashion",
    confidence: "verified",
    confidenceNote: "Real trend resurgence — mob wife aesthetic (#mobwife, 100M+ TikTok views) has re-surged in April 2026 driven by Euphoria Season 3 (premiered April 12, HBO). Maddy Perez's mob wife wardrobe is dominant editorial content: Elle India, Vogue SG, Brit+Co, Who What Wear, NSS G-Club all covered. Search for 'Maddy Euphoria eyeliner' and 'Alexa Demie lipstick' are spiking.",
    description: "Euphoria Season 3 brought Maddy Perez back with a full mob wife wardrobe — faux fur, oversized gold jewellery, bodycon silhouettes, film noir palettes — and TikTok immediately lost it. 'Alexa Demie look' searches hit 1.84M views. The aesthetic revival has real Jibbitz angles: a tiny gold chain charm, stacked rings, or an oversized vintage-style sunglasses silhouette. The sunglasses charm is the strongest — instantly readable, no face or character needed, pure attitude.",
    source: "TikTok / HBO Euphoria S3 / Elle India / Vogue SG / Who What Wear",
    daysTrending: 17,
    momentum: "surging",
    jibbitzScore: 82,
    stage: "evaluation",
    stageDetail: "No licensing needed — mob wife aesthetic is cultural shorthand, not IP. Oversized sunglasses or gold chain charm requires no character rights. Window tied to Euphoria S3 episode run — approximately 8-10 weeks. Move before the finale closes the conversation.",
    searchTrend: [0, 0, 2, 8, 20, 45, 70, 85, 92, 98, 100, 97, 94, 90],
    regional: { US: 0, JP: 0, CN: 0, KR: 0, IN: 0, UK: 0, FR: 0, DE: 0 },
    audience: { "Gen Z": 92, "Millennials": 88, "Parents": 30, "Kids": 15 },
  },
];

const JIBBITZ_PIPELINE = [
  { stage: "watching", label: "Watching", icon: "👁️", color: "#6b7280" },
  { stage: "evaluation", label: "Evaluating", icon: "🔍", color: "#f59e0b" },
  { stage: "launched", label: "Launched", icon: "🚀", color: "#43B02A" },
];

