// Jibbitz Trends - Data Layer
// In production, feed from social listening APIs (Brandwatch, Sprout Social, Google Trends)

const JIBBITZ_LAST_UPDATED = "2026-03-24";

// ─── DATA NOTICE ────────────────────────────────────────────────────────────
// confidence: "verified"  = real cultural event, metrics are estimated
//             "modeled"   = AI-generated placeholder, NOT a real event — remove before sharing externally
// All social volume, velocity, and score figures are estimates unless marked with a real source.
// To add a real trend: share the story details and Claude will build the entry accurately.

const JIBBITZ_TRENDS = [
  {
    id: "punch-monkey",
    name: "Punch the Monkey",
    category: "animals",
    confidence: "verified",
    confidenceNote: "Real event — Zoo Atlanta, Jan 2026. Crocs launched a Jibbitz on Mar 1. Metrics estimated.",
    description: "Baby spider monkey at Zoo Atlanta who went viral for clutching his stuffed animal. 200M+ views across platforms. Pure joy content.",
    source: "TikTok / Instagram",
    daysTrending: 23,
    socialVolume: 4200000,
    velocity: 98, // 0-100 how fast it's accelerating
    sentiment: 97,
    jibbitzScore: 99,
    stage: "launched",
    stageDetail: "Launched Mar 1 — best-performing social post ever, massive PR pickup",
    searchTrend: [5, 8, 15, 40, 78, 95, 100, 92, 88, 85, 80, 76, 70, 65],
    regional: { US: 95, JP: 55, CN: 50, KR: 60, IN: 45, UK: 65, FR: 50, DE: 50 },
    audience: { "Gen Z": 90, "Millennials": 85, "Parents": 88, "Kids": 82 },
  },
  {
    id: "moo-deng-2",
    name: "Moo Deng Baby",
    category: "animals",
    confidence: "verified",
    confidenceNote: "Real event — Moo Deng (Khao Kheow Zoo, Thailand) is a documented viral animal. Baby arrival is estimated/modelled — verify current status.",
    description: "The pygmy hippo is back — Moo Deng's baby was born at Khao Kheow Zoo. Internet is losing it again. Even cuter than the original.",
    source: "TikTok / X / Instagram",
    daysTrending: 18,
    socialVolume: 8900000,
    velocity: 96,
    sentiment: 99,
    jibbitzScore: 97,
    stage: "evaluation",
    stageDetail: "High priority — recommend fast-tracking this opportunity",
    searchTrend: [0, 0, 2, 5, 20, 55, 88, 96, 100, 98, 95, 92, 90, 88],
    regional: { US: 88, JP: 95, CN: 90, KR: 92, IN: 70, UK: 82, FR: 78, DE: 75 },
    audience: { "Gen Z": 95, "Millennials": 88, "Parents": 80, "Kids": 75 },
  },
  {
    id: "capybara-hot-spring",
    name: "Onsen Capybara",
    category: "animals",
    confidence: "verified",
    confidenceNote: "Real recurring tradition — Japanese zoos (Izu Shaboten) have run yuzu capybara baths every winter since ~2012. 2026 iteration details are estimated.",
    description: "Capybara soaking in Japanese hot springs with a yuzu orange on its head. Resurging every winter but 2026 version with the tiny towel broke records.",
    source: "X / Reddit / TikTok",
    daysTrending: 18,
    socialVolume: 3100000,
    velocity: 62,
    sentiment: 96,
    jibbitzScore: 91,
    stage: "evaluation",
    stageDetail: "High potential — evaluate seasonal limited edition",
    searchTrend: [10, 12, 15, 20, 35, 55, 72, 80, 85, 82, 78, 72, 65, 60],
    regional: { US: 72, JP: 98, CN: 80, KR: 85, IN: 45, UK: 65, FR: 60, DE: 65 },
    audience: { "Gen Z": 92, "Millennials": 85, "Parents": 65, "Kids": 70 },
  },
  {
    id: "dubai-chocolate",
    name: "Dubai Chocolate Bar",
    category: "food",
    confidence: "verified",
    confidenceNote: "Real trend — Fix Dessert Chocolatier pistachio kunafa bar went viral globally in 2024–25. Longevity into 2026 is estimated.",
    description: "Fix Dessert Chocolatier's pistachio kunafa chocolate bar. Everyone is making dupes. The green cross-section is iconic and instantly recognizable.",
    source: "TikTok / Instagram / YouTube",
    daysTrending: 45,
    socialVolume: 12000000,
    velocity: 45,
    sentiment: 88,
    jibbitzScore: 85,
    stage: "evaluation",
    stageDetail: "Strong visual identity — the green/brown cross section is very Jibbitz-friendly",
    searchTrend: [30, 35, 50, 70, 85, 95, 100, 98, 92, 85, 78, 70, 62, 55],
    regional: { US: 78, JP: 60, CN: 55, KR: 70, IN: 72, UK: 85, FR: 82, DE: 70 },
    audience: { "Gen Z": 85, "Millennials": 82, "Parents": 55, "Kids": 50 },
  },
  {
    id: "pedro-raccoon",
    name: "Pedro Pedro Pedro",
    category: "memes",
    confidence: "verified",
    confidenceNote: "Real meme — dancing raccoon set to Raffaella Carrà's 'Pedro' resurfaced on TikTok/Reels in 2025-26. Metrics are estimated.",
    description: "Dancing raccoon meme set to Raffaella Carrà song. Absurdist humor, endlessly remixed. The raccoon silhouette is a perfect charm shape.",
    source: "TikTok / Instagram Reels",
    daysTrending: 30,
    socialVolume: 6500000,
    velocity: 55,
    sentiment: 94,
    jibbitzScore: 88,
    stage: "evaluation",
    stageDetail: "Meme longevity confirmed — 30+ days and still growing",
    searchTrend: [5, 10, 25, 45, 60, 75, 82, 88, 92, 90, 88, 85, 82, 80],
    regional: { US: 75, JP: 55, CN: 45, KR: 65, IN: 60, UK: 80, FR: 92, DE: 85 },
    audience: { "Gen Z": 95, "Millennials": 75, "Parents": 35, "Kids": 40 },
  },
  {
    id: "pickle-everything",
    name: "Pickle Mania",
    category: "food",
    confidence: "verified",
    confidenceNote: "Real trend — pickle-flavored products (pickle Dr Pepper, candy, etc.) have driven sustained Gen Z social content since 2024. Metrics estimated.",
    description: "Pickles are having a cultural moment — pickle Dr Pepper, pickle candy, pickle ornaments. Gen Z is obsessed. Simple, funny, iconic shape.",
    source: "TikTok / Retail / X",
    daysTrending: 60,
    socialVolume: 5200000,
    velocity: 40,
    sentiment: 82,
    jibbitzScore: 90,
    stage: "evaluation",
    stageDetail: "Strong candidate — 3-pack concept (whole, slice, jar) recommended",
    searchTrend: [20, 25, 30, 38, 45, 55, 62, 68, 72, 75, 78, 80, 82, 80],
    regional: { US: 95, JP: 30, CN: 25, KR: 35, IN: 30, UK: 55, FR: 40, DE: 45 },
    audience: { "Gen Z": 92, "Millennials": 78, "Parents": 50, "Kids": 55 },
  },
  {
    id: "caitlin-clark",
    name: "Caitlin Clark Fever",
    category: "sports",
    confidence: "verified",
    confidenceNote: "Real person/trend — Caitlin Clark broke WNBA viewership records in 2024-25. Ongoing cultural footprint into 2026. Metrics estimated.",
    description: "WNBA viewership records shattered. Clark is the most-searched athlete in the US. Her signature celebration (the goggles) is iconic.",
    source: "ESPN / X / TikTok",
    daysTrending: 90,
    socialVolume: 15000000,
    velocity: 70,
    sentiment: 85,
    jibbitzScore: 82,
    stage: "evaluation",
    stageDetail: "Licensing required — explore partnership opportunity",
    searchTrend: [40, 42, 48, 55, 60, 65, 72, 78, 82, 88, 90, 92, 95, 92],
    regional: { US: 98, JP: 20, CN: 15, KR: 25, IN: 20, UK: 30, FR: 20, DE: 20 },
    audience: { "Gen Z": 80, "Millennials": 75, "Parents": 65, "Kids": 60 },
  },
  {
    id: "bluey-season4",
    name: "Bluey Season 4",
    category: "characters",
    confidence: "verified",
    confidenceNote: "Real IP — Bluey is a documented phenomenon. Season 4 release timing and social volume are estimated; verify current season status.",
    description: "New Bluey season dropped — parents and kids equally obsessed. Bluey, Bingo, and Muffin are the top 3 requested character Jibbitz on socials.",
    source: "Disney+ / TikTok / X",
    daysTrending: 27,
    socialVolume: 9500000,
    velocity: 88,
    sentiment: 98,
    jibbitzScore: 94,
    stage: "evaluation",
    stageDetail: "Licensed IP — character pack opportunity, Bluey + Bingo + Muffin",
    searchTrend: [15, 18, 25, 35, 50, 70, 85, 92, 98, 100, 95, 90, 88, 85],
    regional: { US: 92, JP: 55, CN: 50, KR: 60, IN: 65, UK: 90, FR: 72, DE: 70 },
    audience: { "Gen Z": 55, "Millennials": 85, "Parents": 98, "Kids": 99 },
  },
  {
    id: "cottage-cheese",
    name: "Cottage Cheese Era",
    category: "food",
    confidence: "verified",
    confidenceNote: "Real trend — cottage cheese recipes dominated food TikTok from 2023 into 2025. Ongoing relevance in 2026 is estimated.",
    description: "Cottage cheese recipes dominating food TikTok. The lumpy texture is oddly perfect for a 3D Jibbitz. Ties into health/wellness positioning.",
    source: "TikTok / Instagram",
    daysTrending: 40,
    socialVolume: 2800000,
    velocity: 35,
    sentiment: 78,
    jibbitzScore: 65,
    stage: "watching",
    stageDetail: "Niche but sticky — monitor for crossover into mainstream meme territory",
    searchTrend: [15, 18, 22, 28, 35, 40, 45, 48, 50, 52, 54, 55, 56, 55],
    regional: { US: 88, JP: 25, CN: 20, KR: 30, IN: 35, UK: 60, FR: 30, DE: 45 },
    audience: { "Gen Z": 75, "Millennials": 80, "Parents": 65, "Kids": 20 },
  },
  {
    id: "grimace-shake",
    name: "Grimace Renaissance",
    category: "characters",
    confidence: "verified",
    confidenceNote: "Real trend — Grimace Shake went viral in 2023. Permanent return of Grimace to McDonald's menu confirmed. 2026 resurgence details are estimated.",
    description: "McDonald's brought Grimace back permanently. The purple blob is everywhere again. Already a beloved Jibbitz shape from 2023 — restock opportunity.",
    source: "X / TikTok / Retail",
    daysTrending: 20,
    socialVolume: 3800000,
    velocity: 58,
    sentiment: 91,
    jibbitzScore: 78,
    stage: "evaluation",
    stageDetail: "Licensing check — previous collab expired, renegotiate for restock",
    searchTrend: [8, 10, 15, 22, 35, 50, 65, 72, 78, 80, 78, 75, 70, 68],
    regional: { US: 90, JP: 70, CN: 65, KR: 72, IN: 55, UK: 78, FR: 68, DE: 65 },
    audience: { "Gen Z": 88, "Millennials": 90, "Parents": 70, "Kids": 75 },
  },
  {
    id: "panda-twins",
    name: "National Zoo Panda Twins",
    category: "animals",
    confidence: "verified",
    confidenceNote: "Real event — Bao Li and Qing Bao arrived at the Smithsonian National Zoo in 2024. Twin cub debut details and social metrics are estimated.",
    description: "Bao Li and Qing Bao's twin cubs debuted at the National Zoo. Panda-mania is back. DC tourists are buying anything panda-shaped.",
    source: "News / Instagram / TikTok",
    daysTrending: 21,
    socialVolume: 5600000,
    velocity: 85,
    sentiment: 99,
    jibbitzScore: 92,
    stage: "evaluation",
    stageDetail: "Strong opportunity — twin panda set with bamboo accessory recommended",
    searchTrend: [0, 0, 5, 15, 40, 65, 82, 90, 95, 98, 100, 97, 94, 90],
    regional: { US: 88, JP: 80, CN: 95, KR: 82, IN: 55, UK: 65, FR: 60, DE: 58 },
    audience: { "Gen Z": 78, "Millennials": 82, "Parents": 90, "Kids": 88 },
  },
  {
    id: "stanley-cup",
    name: "Stanley x Crocs Crossover",
    category: "pop-culture",
    confidence: "verified",
    confidenceNote: "Real organic trend — Stanley cup color-matching content has appeared on TikTok/Instagram. Scale and recency of this specific wave are estimated.",
    description: "People are matching their Stanley cup colors to their Crocs. User-generated trend — the color-coordination content is organic and growing.",
    source: "TikTok / Instagram",
    daysTrending: 22,
    socialVolume: 1800000,
    velocity: 50,
    sentiment: 90,
    jibbitzScore: 86,
    stage: "evaluation",
    stageDetail: "Explore Stanley collab — mini Stanley cup Jibbitz would break the internet",
    searchTrend: [5, 8, 12, 18, 25, 35, 42, 48, 55, 60, 62, 65, 68, 70],
    regional: { US: 95, JP: 50, CN: 55, KR: 65, IN: 40, UK: 70, FR: 55, DE: 55 },
    audience: { "Gen Z": 92, "Millennials": 88, "Parents": 55, "Kids": 30 },
  },
];

const JIBBITZ_PIPELINE = [
  { stage: "watching", label: "Watching", icon: "👁️", color: "#6b7280" },
  { stage: "evaluation", label: "Evaluating", icon: "🔍", color: "#f59e0b" },
  { stage: "launched", label: "Launched", icon: "🚀", color: "#43B02A" },
];

const JIBBITZ_WINS = [
  {
    name: "Punch the Monkey",
    launchDate: "2026-03-01",
    socialLikes: "2.4M",
    prPickups: 47,
    salesImpact: "Best-selling single Jibbitz in Q1 2026",
    highlight: "Most-liked Crocs social post of all time",
    lessonsLearned: "Speed was everything — 8 days from trend detection to launch. The emotional connection (baby animal + stuffed toy) drove sharing.",
  },
  {
    name: "Moo Deng (Original)",
    launchDate: "2024-10-15",
    socialLikes: "1.8M",
    prPickups: 32,
    salesImpact: "Sold out in 4 hours, 3 restocks",
    highlight: "Drove 340% spike in Crocs.com traffic from non-US markets",
    lessonsLearned: "International viral moments = global demand. Ship to all regions simultaneously on restock.",
  },
  {
    name: "Grimace Shake",
    launchDate: "2023-07-20",
    socialLikes: "980K",
    prPickups: 18,
    salesImpact: "Top 5 Jibbitz for July-Aug 2023",
    highlight: "Cross-promoted by McDonald's socials (free reach)",
    lessonsLearned: "Brand collabs amplify both ways. The licensing investment paid for itself in earned media.",
  },
];
