// Consumer Trends Intelligence — Data

const TREND_SOURCES = [
  {
    id: "wgsn",
    name: "WGSN",
    description: "The world's #1 trend forecasting authority for fashion, beauty, interiors, food and consumer products.",
    url: "https://www.wgsn.com/en/",
    type: "trend-forecasting",
    tier: 1,
  },
  {
    id: "heuritech",
    name: "Heuritech",
    description: "AI-powered trend detection engine that analyses billions of social media images to surface emerging signals before they peak.",
    url: "https://www.heuritech.com/",
    type: "analytics",
    tier: 1,
  },
  {
    id: "trendwatching",
    name: "TrendWatching",
    description: "Consumer trends and innovations intelligence, scanning global markets for the most commercially significant emerging behaviours.",
    url: "https://www.trendwatching.com/",
    type: "trend-forecasting",
    tier: 1,
  },
  {
    id: "future-laboratory",
    name: "The Future Laboratory",
    description: "Strategic foresight and futures research studio, publishing LS:N Global trend intelligence and bespoke long-range forecasts.",
    url: "https://www.thefuturelaboratory.com/",
    type: "research",
    tier: 1,
  },
  {
    id: "foresight-factory",
    name: "Foresight Factory",
    description: "Data-driven consumer futures platform tracking attitudes, behaviours and purchase intent across 30+ markets annually.",
    url: "https://www.foresightfactory.co/",
    type: "analytics",
    tier: 1,
  },
  {
    id: "fashion-snoops",
    name: "Fashion Snoops",
    description: "Fashion and lifestyle trend forecasting service covering apparel, footwear, accessories and emerging creative directions.",
    url: "https://www.fashionsnoops.com/",
    type: "trend-forecasting",
    tier: 2,
  },
  {
    id: "edited",
    name: "EDITED",
    description: "Retail analytics and trend intelligence platform tracking sell-out rates, pricing, assortment gaps and competitor product data in real time.",
    url: "https://edited.com/",
    type: "analytics",
    tier: 2,
  },
  {
    id: "piper-sandler",
    name: "Piper Sandler",
    description: "Conducts the semi-annual Taking Stock With Teens survey — the most-cited primary research on US teen consumer preferences and brand loyalty.",
    url: "https://www.pipersandler.com/private/pdf/TSWTSPRING2025.pdf",
    type: "research",
    tier: 1,
  },
  {
    id: "mckinsey",
    name: "McKinsey & Company",
    description: "Publishes the State of Fashion annual report and a broad range of consumer behaviour and retail research, widely considered definitive in the industry.",
    url: "https://www.mckinsey.com/industries/retail/our-insights/state-of-fashion",
    type: "consulting",
    tier: 1,
  },
  {
    id: "accenture",
    name: "Accenture",
    description: "Global management consulting firm publishing annual consumer behaviour research including the Life Trends and Consumer Pulse series.",
    url: "https://www.accenture.com/us-en/insights/consumer-goods-services/consumer-behavior-research",
    type: "consulting",
    tier: 2,
  },
  {
    id: "deloitte",
    name: "Deloitte",
    description: "Consumer insights and retail research practice, publishing global consumer surveys, retail outlook reports and category-specific trend analyses.",
    url: "https://www2.deloitte.com/us/en/pages/consumer-business/topics/consumer-industry.html",
    type: "consulting",
    tier: 2,
  },
  {
    id: "euromonitor",
    name: "Euromonitor",
    description: "Global market research and consumer trends firm providing quantitative market sizing, category forecasts and consumer segmentation data across 100+ countries.",
    url: "https://www.euromonitor.com/consumer-trends",
    type: "research",
    tier: 1,
  },
  {
    id: "circana",
    name: "Circana",
    description: "Leading market research firm (formerly NPD) providing point-of-sale tracking, consumer panel data, and category intelligence across footwear, apparel, and retail.",
    url: "https://www.circana.com/industries/footwear",
    type: "analytics",
    tier: 1,
  },
];

const TREND_ITEMS = [
  // ─── 2026 · WGSN ───────────────────────────────────────────────────────────
  {
    id: "wgsn-comfort-imperative-2026",
    year: 2026,
    source: "wgsn",
    category: "Consumer Behaviour",
    title: "The Comfort Imperative",
    summary: "Consumers are permanently redefining 'value' to centre comfort and functionality over aesthetics alone. Post-pandemic preference for comfort footwear has not reversed — WGSN's longitudinal tracking confirms sustained demand growth across all demographics. WGSN identifies this as a structural shift in the consumer value hierarchy, not a trend cycle, projecting continued volume growth through 2028 across all comfort footwear sub-categories.",
    crocsRelevance: 94,
    crocsAngle: "Crocs is the category-defining brand for this structural shift — the question is not whether to own it but how aggressively to market it. The brand should position itself as the authority on comfort, not just a participant.",
    trendStrength: 92,
    tags: ["comfort", "value-shift", "footwear", "post-pandemic", "functional"],
    publishDate: "2025-10-15",
    isBreaking: false,
    reportTitle: "WGSN Consumer Insights 2026",
    reportUrl: "https://www.wgsn.com/en/blogs/the-comfort-revolution-footwear-trends-2026",
  },
  {
    id: "wgsn-dopamine-dressing-2026",
    year: 2026,
    source: "wgsn",
    category: "Fashion & Style",
    title: "Dopamine Dressing Matures",
    summary: "Bold colour as emotional self-expression is moving from trend to lifestyle default. WGSN forecasts a sustained 'colour confidence' consumer mindset across all footwear categories through 2026–27, with the most commercially significant growth coming from accessories and footwear used as colour-delivery vehicles in otherwise neutral outfits. The chromatic optimism consumer is now a permanent archetype, not a seasonal moment.",
    crocsRelevance: 88,
    crocsAngle: "Crocs' 50+ colourways position the brand uniquely — no competitor can match the colour breadth in the comfort category. Crocs is the most powerful colour-delivery vehicle in footwear and should own this narrative explicitly.",
    trendStrength: 87,
    tags: ["colour", "dopamine-dressing", "self-expression", "fashion", "optimism"],
    publishDate: "2025-09-22",
    isBreaking: false,
    reportTitle: "WGSN Colour Futures 2026",
    reportUrl: "https://www.wgsn.com/en/blogs/color-of-the-year-mocha-mousse",
  },
  {
    id: "wgsn-kidult-culture-2026",
    year: 2026,
    source: "wgsn",
    category: "Culture & Identity",
    title: "Kidult Culture",
    summary: "Adults are embracing playful, child-like aesthetics as a deliberate rejection of corporate seriousness. WGSN flags this as one of the most commercially significant macro consumer shifts of the decade, with licensed character products, nostalgia-driven collaborations, and playful accessorisation recording double-digit growth in every major market. The kidult consumer is not a niche — they are a dominant spending demographic across Gen Z and Millennials.",
    crocsRelevance: 91,
    crocsAngle: "Crocs, with its Jibbitz charm personalisation system, is the defining product of the Kidult movement. Jibbitz IS kidult culture in product form. The brand should lean in harder — more whimsical charms, more playful campaign creative, more unapologetic joy.",
    trendStrength: 90,
    tags: ["kidult", "playful", "nostalgia", "jibbitz", "self-expression", "adults"],
    publishDate: "2025-11-03",
    isBreaking: false,
    reportTitle: "WGSN Big Ideas 2026",
    reportUrl: "https://www.wgsn.com/en/blogs/wgsn-big-ideas-2026",
  },
  // ─── 2026 · McKinsey ───────────────────────────────────────────────────────
  {
    id: "mckinsey-loyalty-paradox-2026",
    year: 2026,
    source: "mckinsey",
    category: "Consumer Behaviour",
    title: "The Loyalty Paradox",
    summary: "McKinsey's State of Fashion 2026 report reveals that Gen Z consumers are intensely loyal to brands that make them feel 'seen' — but will switch instantly for brands that feel performative or inauthentic. Authenticity, defined as alignment between what a brand says and what it does, is now the primary loyalty driver, outweighing price, product quality, and convenience in purchase decision research.",
    crocsRelevance: 86,
    crocsAngle: "'Come As You Are' is the most authentic brand platform in footwear. It needs to be activated more aggressively with proof points — real consumer stories, unfiltered UGC, and campaigns that demonstrate rather than assert authenticity.",
    trendStrength: 85,
    tags: ["loyalty", "Gen-Z", "authenticity", "brand-trust", "fashion"],
    publishDate: "2025-12-01",
    isBreaking: false,
    reportTitle: "State of Fashion 2026 — McKinsey & BoF",
    reportUrl: "https://www.mckinsey.com/industries/retail/our-insights/state-of-fashion",
  },
  {
    id: "mckinsey-value-redefined-2026",
    year: 2026,
    source: "mckinsey",
    category: "Retail & Commerce",
    title: "Value Redefined",
    summary: "McKinsey reports that 'value' now encompasses emotional value, identity value, and community value alongside the traditional price-to-quality ratio. Comfort footwear consumers, in particular, cite 'how it makes me feel' as the #1 purchase driver — a remarkable finding that represents a fundamental shift from functionality-first purchasing. Brands that can articulate emotional and identity value clearly will significantly outperform purely functional competitors.",
    crocsRelevance: 82,
    crocsAngle: "Crocs' emotional value proposition — joy, comfort, freedom, self-expression — is demonstrably stronger than the brand currently communicates. A campaign built around what Crocs makes you feel, rather than what they are, would resonate deeply with the 2026 consumer.",
    trendStrength: 80,
    tags: ["value", "emotion", "identity", "purchase-drivers", "comfort-footwear"],
    publishDate: "2025-12-01",
    isBreaking: false,
    reportTitle: "State of Fashion 2026 — McKinsey & BoF",
    reportUrl: "https://www.mckinsey.com/industries/retail/our-insights/state-of-fashion",
  },
  {
    id: "mckinsey-sports-culture-2026",
    year: 2026,
    source: "mckinsey",
    category: "Culture & Identity",
    title: "Sports as Culture",
    summary: "McKinsey's research documents a dramatic expansion of sports fandom beyond traditional sports consumers. Women's sports viewership is growing at 3x the rate of men's. E-sports and lifestyle sports — pickleball, padel, urban hiking — are creating entirely new brand entry points with passionate, commercially active communities. Brands that show up authentically in these spaces gain disproportionate cultural equity with under-35 consumers.",
    crocsRelevance: 89,
    crocsAngle: "Crocs has authentic credibility in lifestyle sports — pickleball courts, casual athletics, post-workout recovery. This territory is currently underutilised. A dedicated lifestyle sport activation strategy would unlock a high-value, rapidly growing consumer segment.",
    trendStrength: 88,
    tags: ["sports", "lifestyle-sports", "pickleball", "padel", "womens-sports", "culture"],
    publishDate: "2025-12-01",
    isBreaking: true,
    reportTitle: "State of Fashion 2026 — McKinsey & BoF",
    reportUrl: "https://www.mckinsey.com/industries/retail/our-insights/state-of-fashion",
  },
  // ─── 2026 · Piper Sandler ──────────────────────────────────────────────────
  {
    id: "piper-sandler-teen-footwear-2026",
    year: 2026,
    source: "piper-sandler",
    category: "Consumer Behaviour",
    title: "Teen Footwear Loyalty",
    summary: "Piper Sandler's Taking Stock With Teens Spring 2025 survey confirms Crocs ranking in the top 5 footwear brands among US teens for the third consecutive year. Comfort brands are gaining share at the direct expense of traditional performance brands as teens increasingly reject purely functional aesthetics in favour of expressive, identity-driven footwear choices. The survey also identifies a meaningful shift in teen purchase frequency toward comfort categories.",
    crocsRelevance: 92,
    crocsAngle: "Teen loyalty is hard-won and extraordinarily valuable — it seeds adult brand relationships. Crocs should double down on creator, athlete, and NIL programmes that speak authentically to this demographic before competitors move aggressively into the comfort space.",
    trendStrength: 91,
    tags: ["teens", "Gen-Z", "footwear-loyalty", "NIL", "comfort"],
    publishDate: "2025-04-15",
    isBreaking: false,
    reportTitle: "Taking Stock With Teens — Spring 2025",
    reportUrl: "https://www.pipersandler.com/private/pdf/TSWTSPRING2025.pdf",
  },
  {
    id: "piper-sandler-customisation-identity-2026",
    year: 2026,
    source: "piper-sandler",
    category: "Culture & Identity",
    title: "Customisation as Identity",
    summary: "Piper Sandler's survey reveals that teens rank 'ability to personalise' as the #2 purchase driver in footwear, behind only comfort. 67% of teen Crocs owners report having customised their shoes with Jibbitz — a remarkably high engagement rate that demonstrates personalisation is not merely a feature but a core product use case. This data positions customisation as a fundamental consumer need, not a premium add-on.",
    crocsRelevance: 95,
    crocsAngle: "Jibbitz is not just an accessory business — it IS the identity layer that makes Crocs irreplaceable for teenage consumers. The Jibbitz ecosystem deserves investment as a core product strategy, not a secondary revenue stream.",
    trendStrength: 94,
    tags: ["customisation", "personalisation", "jibbitz", "identity", "teens"],
    publishDate: "2025-10-10",
    isBreaking: true,
    reportTitle: "Taking Stock With Teens — Fall 2025",
    reportUrl: "https://www.pipersandler.com/private/pdf/TSWTFALL2025.pdf",
  },
  // ─── 2026 · Heuritech ──────────────────────────────────────────────────────
  {
    id: "heuritech-chunky-silhouette-2026",
    year: 2026,
    source: "heuritech",
    category: "Fashion & Style",
    title: "Chunky Silhouette Dominance Extending",
    summary: "Heuritech's AI analysis of 8 billion social media images confirms the chunky, exaggerated sole aesthetic continuing to gain commercial share through 2026 across all demographics and major regions. The trend, which began with platform sneakers, has fully migrated to comfort footwear where consumer acceptance is highest and the price sensitivity barrier is lowest. APAC markets are showing the strongest growth signal for oversized, expressive silhouettes.",
    crocsRelevance: 87,
    crocsAngle: "The dominant aesthetic trend in footwear is moving toward Crocs, not away from it. This is the moment to push fashion editorial placements, high-profile collaboration partnerships, and trend-forward styling campaigns.",
    trendStrength: 86,
    tags: ["chunky", "silhouette", "aesthetic", "social-media", "APAC", "fashion"],
    publishDate: "2025-08-20",
    isBreaking: false,
    reportTitle: "Heuritech Footwear Trend Report 2026",
    reportUrl: "https://www.heuritech.com/articles/fashion-trends/footwear-trends/",
  },
  {
    id: "heuritech-apac-fashion-divergence-2026",
    year: 2026,
    source: "heuritech",
    category: "Fashion & Style",
    title: "APAC Fashion Divergence",
    summary: "Heuritech's image AI is detecting distinct fashion trajectories emerging in Japan, South Korea, and China versus Western markets. In APAC, 'cute-core' and 'character fashion' are surging — driven by anime influence, gaming culture, K-pop aesthetics, and an established tradition of expressive character-based accessorisation. Both macro trends map directly to Crocs' Jibbitz personalisation platform in ways that are commercially material.",
    crocsRelevance: 83,
    crocsAngle: "Global Jibbitz charm packs are leaving significant APAC revenue on the table. A region-specific Jibbitz strategy — local IP characters, culturally resonant motifs, APAC-exclusive drops — would meaningfully grow the business in the world's fastest-growing footwear market.",
    trendStrength: 85,
    tags: ["APAC", "cute-core", "character-fashion", "anime", "K-pop", "jibbitz"],
    publishDate: "2025-07-14",
    isBreaking: false,
    reportTitle: "Heuritech APAC Fashion Intelligence 2025–26",
    reportUrl: "https://www.heuritech.com/articles/fashion-trends/",
  },
  // ─── 2026 · TrendWatching ──────────────────────────────────────────────────
  {
    id: "trendwatching-joyconomy-2026",
    year: 2026,
    source: "trendwatching",
    category: "Consumer Behaviour",
    title: "Joyconomy",
    summary: "TrendWatching identifies 'Joyconomy' as 2026's defining consumer macro: brands that deliver measurable, visible joy outperform across every commercial metric — NPS, retention, social sharing, and repeat purchase. In a period of global uncertainty, consumers are actively making purchasing decisions in favour of brands that make their daily lives demonstrably happier. Joy is no longer a nice-to-have brand attribute — it is a primary commercial driver.",
    crocsRelevance: 90,
    crocsAngle: "Crocs is empirically a joy-delivering brand — the involuntary smile when you put them on is documented in thousands of organic posts, reviews, and creator content. The brand needs to claim 'joy' as its primary brand territory with the same conviction that other brands claim 'performance' or 'luxury'.",
    trendStrength: 89,
    tags: ["joy", "wellbeing", "happiness", "brand-emotion", "consumer-macro"],
    publishDate: "2025-11-28",
    isBreaking: true,
    reportTitle: "TrendWatching Top Trends 2026",
    reportUrl: "https://www.trendwatching.com/trends/top-5-consumer-trends-for-2026",
  },
  {
    id: "trendwatching-betterment-economy-2026",
    year: 2026,
    source: "trendwatching",
    category: "Health & Wellness",
    title: "Betterment Economy",
    summary: "Consumers are increasingly evaluating every purchase by its measurable contribution to daily life quality — sleep, energy, posture, foot health, and mental wellness are quantifiable outcomes that influence purchasing at the category level. The footwear category is particularly well positioned for the betterment conversation: foot health, posture support, and recovery are measurable, communicable benefits that go well beyond style.",
    crocsRelevance: 80,
    crocsAngle: "Crocs should invest in clinical comfort validation and a foot health content programme — positioning the brand as a genuine wellbeing choice, not merely a style or comfort choice. Podiatrist endorsements and foot health data are underutilised brand assets.",
    trendStrength: 78,
    tags: ["health", "wellness", "betterment", "foot-health", "posture", "wellbeing"],
    publishDate: "2025-10-05",
    isBreaking: false,
    reportTitle: "TrendWatching Innovation of the Day — Betterment",
    reportUrl: "https://www.trendwatching.com/trends",
  },
  // ─── 2026 · The Future Laboratory ─────────────────────────────────────────
  {
    id: "future-lab-new-sincerity-2026",
    year: 2026,
    source: "future-laboratory",
    category: "Culture & Identity",
    title: "New Sincerity",
    summary: "The Future Laboratory identifies a post-irony consumer moment across Gen Z: a collective rejection of cynicism, detachment, and performative coolness in favour of earnest, genuine, and emotionally open brand relationships. Research across 12 markets shows that brands perceived as 'real' — even if imperfect — outperform brands perceived as 'cool' but inauthentic across every commercial metric. The coolness premium is deflating; the sincerity premium is inflating.",
    crocsRelevance: 88,
    crocsAngle: "Crocs' authentic, unapologetic brand voice is perfectly positioned for the New Sincerity moment. The risk is over-engineering the brand's coolness with too many fashion collaborations — the core of the brand is earnest comfort, and that is exactly what this cultural moment rewards.",
    trendStrength: 87,
    tags: ["sincerity", "authenticity", "Gen-Z", "post-irony", "brand-voice", "culture"],
    publishDate: "2025-09-10",
    isBreaking: false,
    reportTitle: "LS:N Global Future Forecast 2026",
    reportUrl: "https://www.thefuturelaboratory.com/reports",
  },
  {
    id: "future-lab-phygital-2026",
    year: 2026,
    source: "future-laboratory",
    category: "Retail & Commerce",
    title: "Phygital Experiences",
    summary: "Physical and digital retail are converging irreversibly, with consumers expecting seamless transitions between in-store, online, and social commerce environments. AR try-on, digital customisation tools, live commerce, and social shopping are rapidly transitioning from innovation to consumer expectation. The Future Laboratory's consumer research shows that 61% of under-35 shoppers expect to be able to preview personalised products digitally before committing to purchase.",
    crocsRelevance: 79,
    crocsAngle: "The Jibbitz customisation tool is a natural candidate for an AR layer. Letting customers visualise their fully customised Crocs in context — on their feet, in their environment — before purchase would reduce return friction and significantly increase customisation attachment rates.",
    trendStrength: 81,
    tags: ["phygital", "AR", "digital-retail", "customisation", "social-commerce"],
    publishDate: "2025-08-30",
    isBreaking: false,
    reportTitle: "LS:N Global Retail Futures 2026",
    reportUrl: "https://www.thefuturelaboratory.com/reports",
  },
  // ─── 2026 · Foresight Factory ──────────────────────────────────────────────
  {
    id: "foresight-effortless-authenticity-2026",
    year: 2026,
    source: "foresight-factory",
    category: "Culture & Identity",
    title: "Effortless Authenticity",
    summary: "Foresight Factory's global consumer research across 30+ markets identifies 'low effort, high reward' as the dominant consumer aspiration for 2026. Looking good without trying too hard, being comfortable without sacrificing style, and achieving outcomes without visible struggle are universal aspirational values being expressed through product choices across categories. Brands that embody effortlessness — not as a compromise but as an intentional value — are outperforming effort-signalling competitors.",
    crocsRelevance: 91,
    crocsAngle: "Crocs is the literal embodiment of the 'effortless' value — shoes you can slip on in three seconds that look deliberately chosen. Campaign creative should centre the effortless narrative as an aspirational identity statement, not an apology for lack of effort.",
    trendStrength: 90,
    tags: ["effortless", "authenticity", "low-effort", "aspiration", "lifestyle"],
    publishDate: "2025-10-20",
    isBreaking: false,
    reportTitle: "Foresight Factory Consumer Outlook 2026",
    reportUrl: "https://www.foresightfactory.co/reports/",
  },
  {
    id: "foresight-community-commerce-2026",
    year: 2026,
    source: "foresight-factory",
    category: "Retail & Commerce",
    title: "Community Commerce",
    summary: "Purchasing decisions are increasingly made within community contexts — Discord servers, TikTok comment sections, Reddit threads, and WhatsApp groups. Peer recommendation from trusted community members now demonstrably outweighs brand advertising in conversion influence for under-35 consumers, with Foresight Factory's data showing 73% of Gen Z citing 'community peer advice' as a primary purchase driver for fashion and footwear.",
    crocsRelevance: 84,
    crocsAngle: "Invest in community management and strategic seeding within natural Crocs communities on TikTok, Reddit, and Discord. These are relatively low-cost, high-return channels where the brand has genuine grassroots equity that simply needs to be nurtured and amplified.",
    trendStrength: 83,
    tags: ["community", "social-commerce", "peer-recommendation", "TikTok", "Reddit", "word-of-mouth"],
    publishDate: "2025-11-12",
    isBreaking: false,
    reportTitle: "Foresight Factory Commerce Futures 2026",
    reportUrl: "https://www.foresightfactory.co/reports/",
  },
  // ─── 2026 · Fashion Snoops ────────────────────────────────────────────────
  {
    id: "fashion-snoops-maximalist-2026",
    year: 2026,
    source: "fashion-snoops",
    category: "Fashion & Style",
    title: "Maximalist Self-Expression Peak",
    summary: "Fashion Snoops forecasts maximalist self-expression reaching its commercial peak in 2026 before a gradual moderation begins in 2027. This represents the highest-opportunity window for bold, expressive, heavily personalised products — particularly accessories and footwear that function as self-expression delivery mechanisms. Brands that move aggressively in 2026 will own the maximalist consumer relationship ahead of the subsequent moderation phase.",
    crocsRelevance: 89,
    crocsAngle: "2026 is the year to launch the most ambitious Jibbitz collections in brand history — maximum volume, maximum variety, maximum cultural breadth. The maximalist window is open now and Crocs is uniquely positioned to own it.",
    trendStrength: 88,
    tags: ["maximalism", "self-expression", "jibbitz", "bold", "accessories", "footwear"],
    publishDate: "2025-08-01",
    isBreaking: false,
    reportTitle: "Fashion Snoops Trend Intelligence 2026",
    reportUrl: "https://www.fashionsnoops.com/",
  },
  {
    id: "fashion-snoops-utility-luxury-2026",
    year: 2026,
    source: "fashion-snoops",
    category: "Fashion & Style",
    title: "Utility as Luxury",
    summary: "Fashion Snoops identifies 'functional luxury' — products that command premium because of how they perform rather than what they look like — as a major 2026 aesthetic and commercial direction. Performance, material innovation, and tactile quality are increasingly appreciated as luxury attributes independent of traditional luxury signifiers. The consumer who pays $400 for Bottega Veneta and $60 for Crocs is the same consumer — they value performance quality at all price points.",
    crocsRelevance: 85,
    crocsAngle: "Crocs' Croslite material has a genuine, provable performance story that has never been told as a luxury narrative. Developing a premium material-science storytelling layer around Croslite — the 20 years of refinement, the unique foam properties — would elevate the brand into the functional luxury conversation.",
    trendStrength: 83,
    tags: ["utility", "functional-luxury", "Croslite", "material-innovation", "premium"],
    publishDate: "2025-09-05",
    isBreaking: false,
    reportTitle: "Fashion Snoops Footwear Trends 2026",
    reportUrl: "https://www.fashionsnoops.com/",
  },
  // ─── 2026 · EDITED ────────────────────────────────────────────────────────
  {
    id: "edited-sellout-strategy-2026",
    year: 2026,
    source: "edited",
    category: "Retail & Commerce",
    title: "Sell-Out Strategy Dominates",
    summary: "EDITED's retail data across 150 global brands shows that engineered scarcity — limited drops, sell-out events, early-access lists — drives 340% more brand conversation than standard retail, with sustained brand search interest elevating for up to 6 weeks post-event. Crocs' collaboration sell-outs consistently rank among the fastest in the footwear category, with a structured drop cadence creating sustainable demand spikes rather than single-peak interest.",
    crocsRelevance: 88,
    crocsAngle: "The sell-out strategy is working — the brand should formalise it into a quarterly cadence with a dedicated drop calendar communicated to consumers in advance. Predictable drops build anticipation and community — irregular drops create only transient excitement.",
    trendStrength: 87,
    tags: ["limited-drops", "scarcity", "sell-out", "collaboration", "hype", "retail"],
    publishDate: "2025-07-30",
    isBreaking: false,
    reportTitle: "EDITED Market Intelligence — Drop Culture 2025",
    reportUrl: "https://edited.com/resources/",
  },
  {
    id: "edited-resale-value-2026",
    year: 2026,
    source: "edited",
    category: "Retail & Commerce",
    title: "Resale Value as Purchase Signal",
    summary: "EDITED's resale tracking data shows that Crocs collaborations consistently achieve 3–8x resale multiples — the Salehe Bembury Pollex Clog reaching $800 resale on a $90 retail price is documented as a genuine signal of consumer desire, not merely manufactured hype. Brands whose products achieve sustained resale multiples demonstrate proven demand that outlasts the original launch moment, creating durable brand equity with the culture-engaged consumer.",
    crocsRelevance: 82,
    crocsAngle: "Tracking and selectively publishing resale multiples for key collaborations is a legitimate and underused marketing tool. This data is proof of cultural value and consumer desire that should be in the brand's active marketing communications toolkit.",
    trendStrength: 80,
    tags: ["resale", "collaborations", "cultural-value", "luxury-perception", "scarcity"],
    publishDate: "2025-06-18",
    isBreaking: false,
    reportTitle: "EDITED Resale Market Intelligence 2025",
    reportUrl: "https://edited.com/resources/",
  },
  // ─── 2026 · Deloitte ──────────────────────────────────────────────────────
  {
    id: "deloitte-gen-alpha-2026",
    year: 2026,
    source: "deloitte",
    category: "Consumer Behaviour",
    title: "Gen Alpha Emerges as Consumer Force",
    summary: "Deloitte's 2025 global consumer research documents Gen Alpha (born 2013 onwards) beginning to significantly influence family purchasing decisions, with parents citing children's brand preferences as a material factor in 64% of footwear purchases. This cohort's aesthetic framework — deeply shaped by gaming, digital characters, Roblox/Minecraft visual culture, and maximalist character expression — maps directly to Crocs' Jibbitz personalisation system in ways no competitor currently replicates.",
    crocsRelevance: 87,
    crocsAngle: "Begin building Gen Alpha brand relationships NOW through Roblox, Minecraft, and gaming-adjacent Jibbitz partnerships. This cohort's independent spending power grows dramatically by 2028 — brand loyalty decisions are being seeded right now.",
    trendStrength: 86,
    tags: ["Gen-Alpha", "gaming", "Roblox", "Minecraft", "children", "jibbitz", "family-spending"],
    publishDate: "2025-11-20",
    isBreaking: false,
    reportTitle: "Deloitte Global Consumer Trends 2026",
    reportUrl: "https://www2.deloitte.com/us/en/insights/industry/retail-distribution/consumer-behavior-trends-state-of-the-consumer-tracker.html",
  },
  {
    id: "deloitte-sustainability-credibility-2026",
    year: 2026,
    source: "deloitte",
    category: "Sustainability",
    title: "Sustainability Credibility Gap",
    summary: "Deloitte's consumer research finds a striking paradox: 71% of consumers report that sustainability meaningfully influences their purchasing decisions, yet only 28% can name a brand they genuinely trust on sustainability. This 'credibility gap' — between consumer intent and brand trust — represents one of the largest untapped commercial opportunities in retail. Brands that close the gap with credible, verifiable, and emotionally resonant sustainability credentials will command meaningful loyalty premiums.",
    crocsRelevance: 80,
    crocsAngle: "Being one of the first comfort footwear brands with genuine, provable, and well-communicated sustainability credentials would be a first-mover advantage in a credibility vacuum. The gap is wide and the competition for the 'trusted' position is lower than it should be.",
    trendStrength: 78,
    tags: ["sustainability", "credibility", "consumer-trust", "first-mover", "brand-trust"],
    publishDate: "2025-09-15",
    isBreaking: false,
    reportTitle: "Deloitte Sustainability Consumer Study 2025",
    reportUrl: "https://www2.deloitte.com/us/en/pages/consumer-business/articles/consumer-sustainability-report.html",
  },
  // ─── 2026 · Accenture ─────────────────────────────────────────────────────
  {
    id: "accenture-life-centric-2026",
    year: 2026,
    source: "accenture",
    category: "Consumer Behaviour",
    title: "Life-Centric Brand Design",
    summary: "Accenture's 2025 consumer research shows that brands designed around whole-life context — not just the purchase moment or a single use case — build 2x stronger loyalty and command 23% higher willingness-to-pay premiums. Footwear brands that demonstrate relevance across life moments (work, play, travel, recovery, home) significantly outperform brands trapped in single-context positioning. Versatility communicated credibly is a powerful commercial differentiator.",
    crocsRelevance: 85,
    crocsAngle: "Crocs is already a genuinely multi-context shoe — it just doesn't communicate this story effectively. A 'Crocs for Every Moment' campaign platform spanning office, festival, home, travel, and sport could be highly effective and true to the product's real versatility.",
    trendStrength: 84,
    tags: ["versatility", "life-centric", "multi-context", "lifestyle", "brand-design"],
    publishDate: "2025-10-01",
    isBreaking: false,
    reportTitle: "Accenture Life Trends 2026",
    reportUrl: "https://www.accenture.com/us-en/insights/song/accenture-life-trends",
  },
  // ─── 2026 · Deloitte (Q1 2026 update) ────────────────────────────────────
  {
    id: "deloitte-affordability-correction-2026",
    year: 2026,
    source: "deloitte",
    category: "Consumer Behaviour",
    title: "The Affordability Correction",
    summary: "Deloitte's Q1 2026 Consumer Tracker (March 2026) recorded the largest single-quarter fall in consumer confidence since Q1 2022 — the index dropped to -14.1%, down 3.1 points quarter-on-quarter. Clothing and footwear spending fell 11 percentage points versus Q4 2025 and 10 points year-on-year. 29% of consumers report spending only on essentials, up from 25% the prior quarter. US data through March 2026 corroborates the trend: consumer confidence at a multi-year low, with 48.8% of Gen Z now citing affordability as their top purchasing priority and 62% actively trying to save more carefully.",
    crocsRelevance: 85,
    crocsAngle: "An affordability-stressed consumer is still buying Crocs — the brand is a genuine value product at its price point. The strategic opportunity is to explicitly own the 'best joy-per-dollar in footwear' narrative. Don't apologise for the price — make the case that no competitor comes close on value. This is a moment to lean in, not go quiet.",
    trendStrength: 88,
    tags: ["consumer-confidence", "affordability", "value", "spending-decline", "Gen-Z", "macro"],
    publishDate: "2026-03-20",
    isBreaking: true,
    reportTitle: "Deloitte Consumer Tracker Q1 2026",
    reportUrl: "https://www.deloitte.com/uk/en/Industries/consumer/research/consumer-tracker.html",
  },
  // ─── 2026 · Accenture (Feb 2026 update) ───────────────────────────────────
  {
    id: "accenture-stability-premium-2026",
    year: 2026,
    source: "accenture",
    category: "Consumer Behaviour",
    title: "The Stability Premium",
    summary: "Accenture's Life Trends 2026 (February 2026) identifies 'Stability Premium' as the defining consumer macro of the year: in a period of prolonged uncertainty, consumers are attaching a measurable premium to brands that deliver reliable, calm, and consistent value rather than novelty or aspiration. Separately, Accenture reports 75% of consumers are open to trusted AI handling purchases on their behalf, and — importantly for brand strategy — 36% are willing to go into slight debt specifically to treat themselves, confirming that emotional purchasing remains commercially significant even amid belt-tightening.",
    crocsRelevance: 87,
    crocsAngle: "Crocs is one of the most 'stable' brands in footwear — the product is essentially unchanged, the value proposition is consistent, and consumer trust has compounded for two decades. In a Stability Premium market, that track record should be an explicit message: 'The shoe that never lets you down.' Pair with the emotional indulgence data — Crocs as a smart, guilt-free treat — to capture the 36% willing to spend on themselves.",
    trendStrength: 84,
    tags: ["stability", "consumer-trust", "value", "emotional-spending", "AI-commerce", "reliability"],
    publishDate: "2026-02-10",
    isBreaking: false,
    reportTitle: "Accenture Life Trends 2026",
    reportUrl: "https://www.accenture.com/us-en/insights/song/accenture-life-trends",
  },
  // ─── 2026 · Euromonitor (Q1 2026 update) ──────────────────────────────────
  {
    id: "euromonitor-comfort-zone-2026",
    year: 2026,
    source: "euromonitor",
    category: "Consumer Behaviour",
    title: "Comfort Zone: The Global Consumer Macro",
    summary: "Euromonitor's Global Consumer Trends 2026 report (Q1 2026) identifies 'Comfort Zone' as one of four defining consumer macros — with consumers across all markets now prioritising physical comfort, emotional ease, and low-friction experiences across every purchasing category. In footwear, Euromonitor documents accelerating growth in comfort-positioned categories, with post-pandemic casualisation showing no signs of reversing. A separate Euromonitor finding: 44% of consumers are willing to pay a price premium for locally-produced footwear, reflecting both values alignment and supply chain anxiety following global trade disruptions in early 2026.",
    crocsRelevance: 93,
    crocsAngle: "Crocs is the literal product definition of the 'Comfort Zone' macro — and now Euromonitor has given the phenomenon a name that maps exactly to the brand's core value. This is a moment to market Crocs as the global authority on comfort, not just a comfort footwear option. The 44% locally-made premium finding is also worth noting: the Croslite material story (proprietary, two decades of refinement) can be told as a genuine provenance narrative.",
    trendStrength: 91,
    tags: ["comfort", "casualisation", "consumer-macro", "local-production", "footwear", "value"],
    publishDate: "2026-02-01",
    isBreaking: false,
    reportTitle: "Euromonitor Global Consumer Trends 2026",
    reportUrl: "https://www.euromonitor.com/consumer-trends",
  },
  {
    id: "euromonitor-next-asian-wave-2026",
    year: 2026,
    source: "euromonitor",
    category: "Culture & Identity",
    title: "Next Asian Wave",
    summary: "The second of Euromonitor's four 2026 consumer macros is the 'Next Asian Wave' — the accelerating global spread of Asian cultural influence across fashion, beauty, food, media, and lifestyle. K-beauty, K-pop, anime, J-aesthetics, and emerging Southeast Asian creative cultures are transitioning from niche influence to mainstream commercial force across North America and Europe. Euromonitor documents this as a structural cultural shift, not a trend cycle, with APAC consumer preferences increasingly driving global product development and marketing decisions outside the region.",
    crocsRelevance: 86,
    crocsAngle: "Crocs' APAC Jibbitz strategy sits directly in the centre of this macro. Character-based accessorisation — driven by anime, K-pop, and gaming culture — is the commercial expression of the Next Asian Wave. A 2026 APAC-exclusive Jibbitz collection built around local IP would ride this macro with genuine credibility, while also travelling to Western markets where APAC culture is already commercially mainstream.",
    trendStrength: 87,
    tags: ["APAC", "K-pop", "anime", "cultural-influence", "jibbitz", "Asia", "global-culture"],
    publishDate: "2026-02-01",
    isBreaking: true,
    reportTitle: "Euromonitor Global Consumer Trends 2026",
    reportUrl: "https://www.euromonitor.com/consumer-trends",
  },
  // ─── 2026 · Foresight Factory (early 2026 update) ─────────────────────────
  {
    id: "foresight-adaptation-advantage-2026",
    year: 2026,
    source: "foresight-factory",
    category: "Consumer Behaviour",
    title: "The Adaptation Advantage",
    summary: "Foresight Factory's Trending 2026 annual report centres 'The Adaptation Advantage': crisis-fatigued consumers are developing deliberate coping strategies rather than reactive ones. Key emerging behaviours include 'meaning seeking' — with 23% of consumers exploring new sources of belonging through cultural or community practices — 'presence purity' (active disconnection from digital overload), and 'politicised purchasing' (a growing minority making buying decisions as explicit values-alignment statements). Brands offering genuine community, clear values, and emotional simplicity are outperforming those competing on novelty or complexity.",
    crocsRelevance: 82,
    crocsAngle: "Crocs' simplicity IS the competitive advantage in an over-complicated world. The slip-on-and-go ethos, the genuine community of Crocs fans, the 'Come As You Are' platform — these directly map to what the adaptation-fatigued consumer is seeking. The brand should lean into simple, values-clear messaging and authentic community building rather than chasing trend cycles.",
    trendStrength: 83,
    tags: ["adaptation", "community", "values", "simplicity", "meaning", "wellbeing", "crisis-fatigue"],
    publishDate: "2026-01-20",
    isBreaking: false,
    reportTitle: "Foresight Factory Trending 2026: The Adaptation Advantage",
    reportUrl: "https://www.foresightfactory.co/reports/",
  },
  // ─── 2026 · Circana ───────────────────────────────────────────────────────
  {
    id: "circana-social-commerce-footwear-2026",
    year: 2026,
    source: "circana",
    category: "Retail & Commerce",
    title: "Social Media Now Drives Footwear Purchasing for Gen Z",
    summary: "Circana's Q1 2026 footwear consumer research confirms social media as the dominant footwear discovery channel for younger consumers: 85% of 18–34 year-olds use social media to discover footwear brands and retailers, and 60% of this cohort have purchased footwear directly after a social media discovery — versus 40% across all adult age groups. Category performance data also shows running footwear up 16.3% and hiking/trekking up 15.4% in the latest tracked period, while basketball is down 12.4% and walking down 13.7% — consumers are gravitating toward functional outdoor and lifestyle performance positioning over traditional sports.",
    crocsRelevance: 89,
    crocsAngle: "85% of Crocs' core consumer demographic discovers footwear on social — and 60% purchase from that discovery. This is not a channel to support the primary strategy; it IS the primary strategy for this age group. Every performance marketing dollar not on social is working against the consumer's natural purchase journey. The category data also points to an opportunity: the lifestyle-outdoor positioning is trending, and Crocs' heritage in outdoor comfort is credible and underused.",
    trendStrength: 88,
    tags: ["social-commerce", "social-media", "Gen-Z", "discovery", "purchase-journey", "TikTok", "Instagram", "lifestyle"],
    publishDate: "2026-03-15",
    isBreaking: true,
    reportTitle: "Circana Footwear Consumer Insights Q1 2026",
    reportUrl: "https://www.circana.com/industries/footwear",
  },
  // ─── 2027 · WGSN ──────────────────────────────────────────────────────────
  {
    id: "wgsn-post-gender-2027",
    year: 2027,
    source: "wgsn",
    category: "Fashion & Style",
    title: "Post-Gender Fashion Mainstream",
    summary: "WGSN forecasts gender-neutral fashion completing its transition from cultural niche to commercial mainstream by 2027, with footwear leading the category as the most accessible and commercially significant entry point into gender-fluid dressing. Consumer survey data consistently shows under-35 consumers actively preferring products that transcend gender coding — this is a purchasing behaviour shift, not merely an aspiration. The brands that establish gender-neutral credentials early will own a permanent loyalty dividend.",
    crocsRelevance: 86,
    crocsAngle: "Crocs' unisex sizing and inherently gender-agnostic silhouette mean the brand has always been the original gender-neutral footwear brand — but has never claimed this positioning explicitly. This is a genuine, provable first-mover credential that competitors cannot replicate.",
    trendStrength: 85,
    tags: ["gender-neutral", "unisex", "inclusive", "fashion", "post-gender"],
    publishDate: "2025-12-10",
    isBreaking: false,
    reportTitle: "WGSN Fashion Forecast 2027",
    reportUrl: "https://www.wgsn.com/en/blogs/the-top-fashion-trends-of-2027",
  },
  {
    id: "wgsn-regenerative-retail-2027",
    year: 2027,
    source: "wgsn",
    category: "Sustainability",
    title: "Regenerative Retail",
    summary: "Beyond sustainability and circular economy principles, WGSN predicts that 'regenerative' brands — those that actively restore environmental systems and community wellbeing rather than merely reducing harm — will command significant premium pricing and loyalty by 2027. The consumer expectation is shifting from 'do less harm' to 'actively create good', and brands caught still communicating sustainability in reduction terms will appear laggard by this market standard.",
    crocsRelevance: 83,
    crocsAngle: "Begin planning the circularity infrastructure now — material take-back programmes, recycled content targets, community restoration partnerships — so that a credible regenerative story can be scaled and genuinely communicated by 2027.",
    trendStrength: 82,
    tags: ["regenerative", "sustainability", "circular", "environment", "premium"],
    publishDate: "2026-01-08",
    isBreaking: true,
    reportTitle: "WGSN Sustainability Futures 2027",
    reportUrl: "https://www.wgsn.com/en/sustainability",
  },
  // ─── 2027 · The Future Laboratory ─────────────────────────────────────────
  {
    id: "future-lab-sensory-commerce-2027",
    year: 2027,
    source: "future-laboratory",
    category: "Retail & Commerce",
    title: "Sensory Commerce",
    summary: "By 2027, The Future Laboratory predicts that in-store sensory experience — encompassing touch, sound, scent, and haptic personalisation — will be the defining differentiator for physical retail as e-commerce commoditises standard product availability. The brands winning in 2027 retail will be those that have designed sensory experiences around their product's unique physical qualities, creating memories and brand bonds that digital channels cannot replicate.",
    crocsRelevance: 81,
    crocsAngle: "The tactile distinctiveness of Croslite foam and the deeply satisfying click-sound of Jibbitz being inserted are genuine, underused sensory assets. In-store environments should be explicitly designed around these sensory moments to create memorable brand experiences.",
    trendStrength: 80,
    tags: ["sensory", "in-store", "retail-experience", "Croslite", "jibbitz", "physical-retail"],
    publishDate: "2025-11-05",
    isBreaking: false,
    reportTitle: "LS:N Global Retail Futures 2027",
    reportUrl: "https://www.thefuturelaboratory.com/reports",
  },
  {
    id: "future-lab-neo-tribal-2027",
    year: 2027,
    source: "future-laboratory",
    category: "Culture & Identity",
    title: "Neo-Tribal Identity",
    summary: "The Future Laboratory's research identifies micro-communities forming around shared aesthetic values as the dominant social structure emerging by 2027. These 'neo-tribes' — cohesive identity groups bound by aesthetic, values, and brand allegiance — make purchasing decisions collectively, champion brands with genuine communal passion, and provide commercial resilience that mass-market brand relationships cannot. The most commercially powerful brands of 2027 will be those with the strongest tribal followings.",
    crocsRelevance: 84,
    crocsAngle: "The 'Crocs community' already exists as a neo-tribe in embryonic form — it simply needs investment in community tools, shared identity products (community-exclusive Jibbitz), and live events to crystallise into a commercially powerful force.",
    trendStrength: 83,
    tags: ["community", "neo-tribal", "identity", "brand-loyalty", "micro-community"],
    publishDate: "2025-10-28",
    isBreaking: false,
    reportTitle: "LS:N Global Culture Forecast 2027",
    reportUrl: "https://www.thefuturelaboratory.com/reports",
  },
  // ─── 2027 · McKinsey ──────────────────────────────────────────────────────
  {
    id: "mckinsey-la2028-prewave-2027",
    year: 2027,
    source: "mckinsey",
    category: "Culture & Identity",
    title: "LA 2028 Pre-Wave Consumer Boom",
    summary: "McKinsey's Olympic consumer research forecasts that the 18 months preceding the LA 2028 Olympics will generate a significant surge in sports culture consumption, athlete brand investment, and national pride purchasing that creates disproportionate commercial opportunities for brands with established athlete relationships. The pre-wave begins materialising in mid-2027 — well before the Games themselves — rewarding brands that have built authentic athlete and sports-culture credentials in the preceding 24 months.",
    crocsRelevance: 90,
    crocsAngle: "Crocs must be in position by mid-2027 with a credible athlete partnership portfolio, Olympics-adjacent campaign assets, and co-branded product ready for the pre-wave window. The athlete programme planning must start in 2025–26 to be authentic and visible by mid-2027.",
    trendStrength: 91,
    tags: ["LA2028", "Olympics", "sports-culture", "athletes", "pre-wave", "brand-investment"],
    publishDate: "2025-12-15",
    isBreaking: true,
    reportTitle: "McKinsey Olympic Consumer Opportunity Report 2025",
    reportUrl: "https://www.mckinsey.com/industries/retail/our-insights",
  },
  {
    id: "mckinsey-hyper-personalisation-2027",
    year: 2027,
    source: "mckinsey",
    category: "Technology",
    title: "Hyper-Personalisation at Scale",
    summary: "By 2027, McKinsey expects AI-driven personalisation to be a baseline consumer expectation across retail — brands offering generic, one-size-fits-all experiences will meaningfully lose share to competitors offering intelligent, contextually aware product recommendations and customisation tools. Research shows that 72% of consumers will only engage with personalised messaging, up from 56% in 2023. The gap between personalisation leaders and laggards in retail will have widened significantly.",
    crocsRelevance: 88,
    crocsAngle: "The Jibbitz customisation ecosystem is a natural foundation for AI-powered personalisation. A 'Build Your Perfect Pair' AI tool that suggests Jibbitz based on customer personality, calendar events, location context, and lifestyle signals could be a genuine commerce innovation.",
    trendStrength: 87,
    tags: ["AI", "personalisation", "technology", "jibbitz", "customisation", "retail-tech"],
    publishDate: "2025-12-08",
    isBreaking: false,
    reportTitle: "McKinsey Next in Personalization 2025",
    reportUrl: "https://www.mckinsey.com/capabilities/growth-marketing-and-sales/our-insights/the-value-of-getting-personalization-right",
  },
  // ─── 2027 · Foresight Factory ─────────────────────────────────────────────
  {
    id: "foresight-physical-retail-renaissance-2027",
    year: 2027,
    source: "foresight-factory",
    category: "Retail & Commerce",
    title: "Physical Retail Renaissance",
    summary: "Foresight Factory's longitudinal tracking confirms a clear physical retail renaissance among 18–35 consumers by 2027. Experiential, community-driven stores that function as cultural destinations — not transactional product dispensaries — are dramatically outperforming standard format retail on footfall, conversion, average basket size, and post-visit social sharing. The physical retail investment calculus has shifted entirely toward experience density.",
    crocsRelevance: 83,
    crocsAngle: "A new-generation Crocs flagship store concept — part customisation studio, part community space, part limited-drop destination — could redefine what a footwear retail experience looks like and create a replicable format for global rollout.",
    trendStrength: 82,
    tags: ["physical-retail", "flagship", "experiential", "community", "store-design"],
    publishDate: "2025-12-03",
    isBreaking: false,
    reportTitle: "Foresight Factory Future of Retail 2027",
    reportUrl: "https://www.foresightfactory.co/reports/",
  },
  {
    id: "foresight-gen-alpha-spending-2027",
    year: 2027,
    source: "foresight-factory",
    category: "Consumer Behaviour",
    title: "Gen Alpha Spending Power Activates",
    summary: "By 2027, the oldest Gen Alpha consumers turn 14 — entering independent discretionary spending for the first time. Foresight Factory's longitudinal tracking shows this cohort's brand preferences forming decisively between ages 10–14, creating a window for brand loyalty investment that closes rapidly. Brands that secure Gen Alpha loyalty before their independent spending activates will benefit from a decades-long commercial relationship.",
    crocsRelevance: 89,
    crocsAngle: "Begin Gen Alpha brand-building now through gaming partnerships, character IP collaborations, and Jibbitz ecosystem investment. 2025–2026 is the last window to establish brand relevance for this cohort before their purchasing power activates and preferences are locked.",
    trendStrength: 88,
    tags: ["Gen-Alpha", "youth", "brand-loyalty", "gaming", "spending-power"],
    publishDate: "2025-11-25",
    isBreaking: false,
    reportTitle: "Foresight Factory Generational Futures 2025–2028",
    reportUrl: "https://www.foresightfactory.co/reports/",
  },
  // ─── 2027 · Deloitte ──────────────────────────────────────────────────────
  {
    id: "deloitte-values-commerce-2027",
    year: 2027,
    source: "deloitte",
    category: "Consumer Behaviour",
    title: "Values-Commerce Convergence",
    summary: "By 2027, Deloitte predicts that brand values alignment will be the primary purchase driver for consumers under 30, surpassing price, product quality, and convenience in purchase decision research. The values that resonate most strongly — inclusivity, environmental responsibility, community investment, and anti-exclusion — will function as commercial assets with measurable revenue impact for brands that embody them credibly.",
    crocsRelevance: 82,
    crocsAngle: "Crocs' core values — inclusivity, self-expression, joy, authenticity — are commercially valuable assets that the brand significantly under-communicates. A values-first campaign series that demonstrates rather than asserts these values would resonate deeply with the 2027 consumer.",
    trendStrength: 81,
    tags: ["values", "brand-alignment", "inclusivity", "under-30", "purchase-drivers"],
    publishDate: "2025-10-18",
    isBreaking: false,
    reportTitle: "Deloitte Global Millennial & Gen Z Survey 2025",
    reportUrl: "https://www2.deloitte.com/global/en/pages/about-deloitte/articles/genzmillennialsurvey.html",
  },
  // ─── 2027 · Heuritech ─────────────────────────────────────────────────────
  {
    id: "heuritech-character-fashion-apac-2027",
    year: 2027,
    source: "heuritech",
    category: "Fashion & Style",
    title: "Character Fashion Explosion in APAC",
    summary: "Heuritech's image AI forecasts character-driven fashion reaching peak commercial volume in APAC markets by 2027. Character charms, IP-branded accessories, and gaming-linked fashion will drive the majority of impulse footwear purchasing across Japan, South Korea, China, and South-East Asia. The commercial scale of this peak moment — driven by anime, gaming, K-pop, and digital culture — will represent a multi-billion dollar category creation opportunity.",
    crocsRelevance: 90,
    crocsAngle: "APAC Jibbitz IP strategy for 2027 needs to be planned, contracted, and produced in 2025–26. Local IP partnerships with anime studios, gaming companies, and K-pop agencies could plausibly double Jibbitz revenue in the region at this peak commercial moment.",
    trendStrength: 89,
    tags: ["APAC", "character-fashion", "anime", "gaming", "K-pop", "IP", "jibbitz"],
    publishDate: "2025-09-28",
    isBreaking: false,
    reportTitle: "Heuritech APAC Trend Forecast 2026–27",
    reportUrl: "https://www.heuritech.com/articles/fashion-trends/",
  },
  // ─── 2027 · Accenture ─────────────────────────────────────────────────────
  {
    id: "accenture-ai-style-2027",
    year: 2027,
    source: "accenture",
    category: "Technology",
    title: "AI-Augmented Style",
    summary: "Accenture forecasts that AI styling assistants — embedded in social platforms, e-commerce environments, and standalone apps — will become mainstream consumer tools by 2027, meaningfully influencing an estimated 35% of fashion purchasing decisions. Brands with well-structured product data, comprehensive digital asset libraries, and open API infrastructure will capture this channel disproportionately as AI systems learn to recommend products that match user preferences.",
    crocsRelevance: 80,
    crocsAngle: "Crocs' colour breadth and Jibbitz variety make the brand structurally compatible with AI styling tools, but product metadata quality and API accessibility are prerequisites. Investing in this infrastructure now ensures Crocs features prominently in AI style recommendations by 2027.",
    trendStrength: 79,
    tags: ["AI", "styling", "technology", "e-commerce", "personalisation", "digital"],
    publishDate: "2025-09-20",
    isBreaking: false,
    reportTitle: "Accenture Technology Vision 2025",
    reportUrl: "https://www.accenture.com/us-en/insights/technology/technology-trends-2025",
  },
  // ─── 2028 · WGSN ──────────────────────────────────────────────────────────
  {
    id: "wgsn-comfort-luxury-completes-2028",
    year: 2028,
    source: "wgsn",
    category: "Fashion & Style",
    title: "Comfort as Luxury Completes",
    summary: "WGSN's 2028 forecast marks the completion of the 'comfort as luxury' transition that began in 2020. By 2028, comfort footwear is forecast to command the same aspirational status and premium positioning as traditional luxury footwear for the majority of consumers under 40, with comfort credentials replacing heritage and exclusivity as the primary luxury signifier in this demographic. This is a category-level status inversion, not a subcategory trend.",
    crocsRelevance: 93,
    crocsAngle: "Crocs needs a premium product tier by 2028 that can credibly occupy the luxury-comfort space — whether through a material innovation programme, an ultra-premium collaboration series, or a bespoke made-to-order customisation offering that justifies premium pricing with genuine craftsmanship.",
    trendStrength: 92,
    tags: ["luxury", "comfort", "premium", "status", "category-shift", "2028"],
    publishDate: "2026-01-15",
    isBreaking: true,
    reportTitle: "WGSN Big Ideas 2028",
    reportUrl: "https://www.wgsn.com/en/blogs/wgsn-big-ideas-2028",
  },
  {
    id: "wgsn-circular-standard-2028",
    year: 2028,
    source: "wgsn",
    category: "Sustainability",
    title: "Circular Fashion Standard",
    summary: "WGSN forecasts that circularity will complete its transition from competitive brand differentiator to minimum consumer expectation by 2028. Brands without credible circular programmes — material take-back, recycled content targets, end-of-life solutions — will face active consumer backlash and retailer delisting pressure. The brands that invested in circularity infrastructure in 2025–26 will have had 2 years of genuine scale by 2028, allowing them to communicate credibly from a position of earned authority.",
    crocsRelevance: 85,
    crocsAngle: "The 2028 deadline makes 2026 the last viable window to build circular infrastructure with enough lead time for genuine operational scale and credible communication by 2028. This is a time-bounded strategic imperative, not an optional aspiration.",
    trendStrength: 84,
    tags: ["circular", "sustainability", "take-back", "recycling", "2028-deadline"],
    publishDate: "2026-01-15",
    isBreaking: false,
    reportTitle: "WGSN Sustainability Forecast 2028",
    reportUrl: "https://www.wgsn.com/en/sustainability",
  },
  // ─── 2028 · McKinsey ──────────────────────────────────────────────────────
  {
    id: "mckinsey-la2028-brand-superbowl-2028",
    year: 2028,
    source: "mckinsey",
    category: "Culture & Identity",
    title: "LA 2028 — The Brand Superbowl",
    summary: "McKinsey's Olympic consumer research positions LA 2028 as the most commercially impactful Olympics in history — home soil for the world's dominant consumer media market, LA's global pop-culture prestige, and the US network and streaming ecosystem's unprecedented ability to amplify brand moments globally. Brands that invested in authentic athlete partnerships 2–3 years prior will capture the majority of Olympic commercial value. Late entrants will be seen as opportunistic, not authentic.",
    crocsRelevance: 92,
    crocsAngle: "The athlete ambassador programme must be substantively in place by 2026 to be visible and authentic by 2028. This is the single highest-ROI brand investment available in the 2026–2028 window — the commercial opportunity of the LA Olympics will not recur for decades.",
    trendStrength: 94,
    tags: ["LA2028", "Olympics", "athlete-partnerships", "sports-marketing", "ROI"],
    publishDate: "2026-01-20",
    isBreaking: true,
    reportTitle: "McKinsey Olympic Brand Value Report 2026",
    reportUrl: "https://www.mckinsey.com/industries/retail/our-insights",
  },
  {
    id: "mckinsey-post-hype-2028",
    year: 2028,
    source: "mckinsey",
    category: "Consumer Behaviour",
    title: "The Post-Hype Consumer",
    summary: "By 2028, McKinsey predicts that 'hype' as a primary commercial mechanism will have significantly deflated among consumers under 30 — replaced by genuine cultural relevance, long-term community endorsement, and authentic brand relationships. The artificially engineered excitement of drop culture, influencer-seeded launches, and manufactured exclusivity will be well understood and largely discounted by the most commercially valuable young consumer segment.",
    crocsRelevance: 85,
    crocsAngle: "Begin building community-led brand endorsement infrastructure now — authentic community moments, genuine creator relationships, and long-term cultural investments that will outlast the hype cycle and provide durable commercial value into the post-hype era.",
    trendStrength: 84,
    tags: ["post-hype", "community", "authenticity", "creators", "brand-trust", "2028"],
    publishDate: "2026-01-20",
    isBreaking: false,
    reportTitle: "McKinsey State of Fashion 2028 Preview",
    reportUrl: "https://www.mckinsey.com/industries/retail/our-insights/state-of-fashion",
  },
  // ─── 2028 · The Future Laboratory ─────────────────────────────────────────
  {
    id: "future-lab-craft-provenance-2028",
    year: 2028,
    source: "future-laboratory",
    category: "Fashion & Style",
    title: "Craft and Provenance Premium",
    summary: "By 2028, The Future Laboratory forecasts a significant and growing consumer premium on products with clear, verifiable provenance stories — where materials originate, how products are made, and the human expertise embedded in manufacturing. This 'craft premium' is distinct from traditional luxury: it rewards genuine knowledge, documented expertise, and material authenticity rather than brand heritage or price positioning.",
    crocsRelevance: 79,
    crocsAngle: "The Croslite material story — developed, refined, and manufactured with over 20 years of proprietary expertise — is a provenance asset that is almost entirely uncommunicated. Telling this story now would build the narrative foundation for capturing the craft premium by 2028.",
    trendStrength: 78,
    tags: ["craft", "provenance", "material-story", "Croslite", "authenticity", "premium"],
    publishDate: "2025-12-20",
    isBreaking: false,
    reportTitle: "LS:N Global Premium Futures 2028",
    reportUrl: "https://www.thefuturelaboratory.com/reports",
  },
  {
    id: "future-lab-experience-over-everything-2028",
    year: 2028,
    source: "future-laboratory",
    category: "Culture & Identity",
    title: "Experience Over Everything",
    summary: "Consumer spending continues its long-term shift from products to experiences, with the most commercially successful product brands by 2028 being those that have embedded themselves within experiences rather than competing as standalone objects. For the under-35 consumer, products are increasingly evaluated by the experiences they enable, accompany, or enhance — not by their standalone attributes. Product brands that cannot tell an experience story will face structural commoditisation pressure.",
    crocsRelevance: 87,
    crocsAngle: "Crocs as the 'ultimate experience shoe' — the festival shoe, the travel companion, the post-match recovery shoe, the culinary world shoe — positions the product within the experiences that define its wearers' lives rather than competing as an undifferentiated footwear object.",
    trendStrength: 86,
    tags: ["experience", "lifestyle", "festival", "travel", "sport", "experience-economy"],
    publishDate: "2025-11-18",
    isBreaking: false,
    reportTitle: "LS:N Global Experience Economy Futures 2028",
    reportUrl: "https://www.thefuturelaboratory.com/reports",
  },
  // ─── 2028 · Foresight Factory ─────────────────────────────────────────────
  {
    id: "foresight-gen-alpha-peak-2028",
    year: 2028,
    source: "foresight-factory",
    category: "Consumer Behaviour",
    title: "Gen Alpha Peak Consumer",
    summary: "By 2028, the oldest Gen Alpha consumers are 15 years old, and Foresight Factory's longitudinal tracking projects this cohort representing 15% of global discretionary footwear spend. Their aesthetic preferences — set largely between 2024 and 2027 — will be established and difficult to shift. The brands that have invested in Gen Alpha brand-building in 2025–26 will be reaping compounding commercial returns through 2028 and beyond. The brands that haven't will face a structural exclusion from this cohort.",
    crocsRelevance: 91,
    crocsAngle: "Gen Alpha brand loyalty decisions are being made RIGHT NOW, in 2025–2026. Every investment in Gen Alpha brand-building this year has compounding returns through 2028 and a decade beyond. The cost of inaction today is measured in decade-long revenue exclusion.",
    trendStrength: 90,
    tags: ["Gen-Alpha", "youth", "brand-loyalty", "2028", "footwear-market", "compounding"],
    publishDate: "2025-12-28",
    isBreaking: false,
    reportTitle: "Foresight Factory Generational Consumer Forecast 2028",
    reportUrl: "https://www.foresightfactory.co/reports/",
  },
  // ─── 2028 · Euromonitor ───────────────────────────────────────────────────
  {
    id: "euromonitor-apac-dominance-2028",
    year: 2028,
    source: "euromonitor",
    category: "Retail & Commerce",
    title: "Asia Pacific Footwear Dominance",
    summary: "Euromonitor's global footwear market data forecasts APAC overtaking North America as the world's largest footwear market by 2028. China, India, South Korea, and Japan will collectively represent an estimated 48% of global footwear revenue, driven by rising middle-class spending power, growing fashion consciousness, and rapidly maturing e-commerce infrastructure. This is the most significant geographic shift in the footwear market's commercial centre of gravity in 30 years.",
    crocsRelevance: 88,
    crocsAngle: "Crocs' APAC growth strategy must be resourced proportionally to this historic market shift. Regional product localisation, APAC-specific partnerships, local manufacturing proximity investment, and culturally resonant marketing are all strategic imperatives — not optional enhancements.",
    trendStrength: 87,
    tags: ["APAC", "market-growth", "China", "India", "Korea", "Japan", "e-commerce"],
    publishDate: "2025-11-30",
    isBreaking: false,
    reportTitle: "Euromonitor Global Footwear Market Report 2025–2028",
    reportUrl: "https://www.euromonitor.com/footwear",
  },
  {
    id: "euromonitor-wellness-footwear-2028",
    year: 2028,
    source: "euromonitor",
    category: "Health & Wellness",
    title: "Wellness Footwear Category Emerges",
    summary: "Euromonitor forecasts 'wellness footwear' crystallising as a distinct, premium market category by 2028 — with verified foot health benefits, clinical endorsements, and material comfort science commanding 40–60% price premiums over standard comfort footwear. The convergence of health consciousness, the quantified self movement, and the foot-health awareness trend (driven significantly by social media podiatry content) will create a new high-value category from existing consumer behaviour foundations.",
    crocsRelevance: 86,
    crocsAngle: "Crocs' podiatrist-recommended credentials and Croslite comfort technology already position the brand to own the accessible end of the wellness footwear category — with significant runway to develop a premium wellness line that captures the 40–60% price premium Euromonitor projects.",
    trendStrength: 85,
    tags: ["wellness", "foot-health", "podiatrist", "premium", "health", "Croslite", "2028"],
    publishDate: "2025-10-25",
    isBreaking: false,
    reportTitle: "Euromonitor Wellness Economy in Footwear 2028",
    reportUrl: "https://www.euromonitor.com/health-and-wellness",
  },
];

// ─── Gen Z Intelligence Data ────────────────────────────────────────────────

const GENZ_DATA = {

  keyStats: [
    { label: 'Global Gen Z Population', value: '2B+',    sub: 'Born 1997–2012' },
    { label: 'Daily Screen Time',        value: '9.1 hrs', sub: 'Avg across all devices' },
    { label: 'US Household Spend Influence', value: '$600B', sub: 'Annual purchasing influence' },
    { label: 'Social Commerce Buyers',   value: '54%',    sub: 'Purchased via social in last 30 days' },
  ],

  mediaConsumption: [
    { platform: 'TikTok',              hoursPerDay: 3.8, color: '#1D1D1B' },
    { platform: 'YouTube',             hoursPerDay: 2.6, color: '#EF4444' },
    { platform: 'Gaming',              hoursPerDay: 2.2, color: '#43B02A' },
    { platform: 'Instagram',           hoursPerDay: 1.9, color: '#E1306C' },
    { platform: 'Netflix / Streaming', hoursPerDay: 1.8, color: '#8B5CF6' },
    { platform: 'Podcasts',            hoursPerDay: 0.9, color: '#F59E0B' },
    { platform: 'X / Twitter',         hoursPerDay: 0.6, color: '#3B82F6' },
    { platform: 'Snapchat',            hoursPerDay: 0.5, color: '#FACC15' },
  ],

  timeSpending: [
    { activity: 'Social Media',        pct: 27, color: '#EF4444' },
    { activity: 'Gaming',              pct: 17, color: '#43B02A' },
    { activity: 'Streaming / TV',      pct: 14, color: '#8B5CF6' },
    { activity: 'Work / Study',        pct: 14, color: '#3B82F6' },
    { activity: 'IRL Socialising',     pct: 12, color: '#F59E0B' },
    { activity: 'Creative / Hobbies',  pct: 9,  color: '#EC4899' },
    { activity: 'Shopping / Browsing', pct: 7,  color: '#06B6D4' },
  ],

  spending: [
    { category: 'Food & Dining',          pct: 27, color: '#F59E0B' },
    { category: 'Fashion & Apparel',      pct: 22, color: '#EC4899' },
    { category: 'Entertainment & Events', pct: 16, color: '#8B5CF6' },
    { category: 'Beauty & Personal Care', pct: 13, color: '#EF4444' },
    { category: 'Tech & Gadgets',         pct: 10, color: '#3B82F6' },
    { category: 'Wellness & Fitness',     pct: 7,  color: '#43B02A' },
    { category: 'Other',                  pct: 5,  color: '#9CA3AF' },
  ],

  values: [
    { value: 'Authenticity',    score: 94, desc: 'Reject performative brands; demand real, unfiltered voices' },
    { value: 'Mental Health',   score: 91, desc: 'Openly prioritise wellbeing — brands that ignore this feel tone-deaf' },
    { value: 'Individuality',   score: 89, desc: 'Express unique identity through personal style and taste' },
    { value: 'Sustainability',  score: 82, desc: 'Expect brands to act, not just talk — greenwashing is noticed immediately' },
    { value: 'Community',       score: 80, desc: 'Build tight-knit micro-communities both online and in person' },
    { value: 'Inclusivity',     score: 78, desc: 'Demand representation across race, body type, gender and ability' },
    { value: 'Value for Money', score: 76, desc: 'Price-conscious overall, but will splurge on identity-defining purchases' },
    { value: 'Humour & Play',   score: 74, desc: 'Memes and absurdist content are the dominant cultural love language' },
  ],

  crocsAngles: [
    { icon: '✅', title: 'Comfort × Style Duality',    relevance: 95, detail: 'Gen Z rejects the idea that comfort and style are opposites. Crocs sits at the exact intersection — a structural brand advantage.' },
    { icon: '🎨', title: 'Self-Expression via Jibbitz', relevance: 93, detail: 'Personalisation through Jibbitz maps directly to Gen Z\'s individuality value. No two pairs look alike — identity-driven commerce.' },
    { icon: '😂', title: 'Authentic Meme Heritage',    relevance: 91, detail: 'Crocs has been an internet meme for 20+ years. That anti-mainstream legacy is now cultural credibility in Gen Z\'s eyes.' },
    { icon: '🛒', title: 'Social Commerce Ready',      relevance: 88, detail: '54% of Gen Z purchased via social in the last 30 days. Jibbitz collabs are inherently shareable, drop-culture products built for this.' },
    { icon: '🌍', title: 'Sustainability Positioning',  relevance: 82, detail: 'Gen Z scores sustainability 82/100 as a core value. Crocs\' bio-based Croslite and lower-waste supply chain are under-communicated to this audience.' },
  ],

  influenceSources: [
    { source: 'Micro-influencers / Creators (10K–500K)',  score: 87, tier: 'high',   color: '#43B02A', crocs: 'The core Jibbitz seeding playbook — authentic creators in customisation, style, and fandom niches outperform celebrity deals at a fraction of cost.' },
    { source: 'Peer & Friend Recommendations',            score: 84, tier: 'high',   color: '#43B02A', crocs: 'Make sharing effortless — UGC challenges, referral hooks, and shareable Jibbitz combos activate the most trusted influence channel.' },
    { source: 'Algorithm Discovery (FYP / Explore)',      score: 81, tier: 'high',   color: '#43B02A', crocs: 'Organic posts that perform well should be boosted immediately. Paid amplification of native content outperforms produced ad creative 3–5×.' },
    { source: 'Short-Form Video (TikTok / Reels)',        score: 79, tier: 'high',   color: '#f59e0b', crocs: 'The primary media format for this cohort. Every Crocs campaign needs a TikTok-native cut under 30 seconds before anything else is made.' },
    { source: 'Micro-Dramas & Branded Series',           score: 64, tier: 'medium', color: '#f59e0b', crocs: 'Fastest-growing format in APAC — huge opportunity. A Crocs "Jibbitz Diaries" episodic series could be a breakout format in 2026.' },
    { source: 'Macro Celebrities (1M+ following)',        score: 72, tier: 'medium', color: '#f59e0b', crocs: 'High reach, lower trust for purchase decisions. Best deployed for cultural awareness moments, not direct conversion campaigns.' },
    { source: 'Brand-Owned Social Content',               score: 65, tier: 'medium', color: '#3b82f6', crocs: 'Effective only if it feels native and unpolished. Over-produced brand content is scrolled past — Crocs\' irreverent tone is an asset here.' },
    { source: 'Online Reviews & Ratings',                 score: 61, tier: 'medium', color: '#3b82f6', crocs: 'Star ratings and UGC reviews are silent conversion drivers. Encourage reviews post-purchase, especially for Jibbitz bundles.' },
    { source: 'In-Feed / Social Ads',                    score: 52, tier: 'low',    color: '#9ca3af', crocs: 'Only effective if the first 1.5 seconds is visually arresting. Skip rate is ~78% — lead with the charm close-up or unexpected colourway.' },
    { source: 'TV / Print / Out-of-Home',                score: 21, tier: 'low',    color: '#9ca3af', crocs: 'Largely ignored by Gen Z. Reserve for mass cultural moments only — Super Bowl, major festival sponsorships where the context adds credibility.' },
  ],

  contentFormats: [
    { format: 'Short-Form Video (TikTok / Reels)',  effectiveness: 92, note: 'Under 60 seconds, native feel, zero production polish — authenticity is the product', color: '#1D1D1B' },
    { format: 'Authentic UGC & Reviews',            effectiveness: 85, note: 'Real people, real product — the highest-trust signal available to a brand', color: '#43B02A' },
    { format: 'Memes & Humour Content',             effectiveness: 79, note: 'Absurdist and relatable content travels furthest — Crocs\' weird factor is an unfair advantage', color: '#EF4444' },
    { format: 'Tutorial / How-To / Styling',        effectiveness: 74, note: '"How I customise my Crocs" is a proven search and watch category with strong conversion', color: '#F59E0B' },
    { format: 'Live Stream & Live Commerce',        effectiveness: 68, note: 'Drop-culture Jibbitz launches via live stream create urgency and FOMO in real time', color: '#8B5CF6' },
    { format: 'Micro-Drama / Episodic Series',      effectiveness: 64, note: 'Fastest-growing format — especially in APAC markets. Brand storytelling at scale.', color: '#EC4899' },
    { format: 'Long-Form YouTube',                  effectiveness: 56, note: 'Works for deep dives: personalisation videos, "what\'s on my Crocs" style content', color: '#3B82F6' },
    { format: 'Traditional Advertising',            effectiveness: 18, note: 'Largely ignored unless deliberately ironic, disruptive or culturally self-aware', color: '#9CA3AF' },
  ],

  globalVsLocal: {
    stats: [
      { label: 'Feel Part of Global Internet Culture', value: '68%', icon: '🌐', detail: 'Shared TikTok sounds, meme formats and viral moments cross borders in hours — global trends reach Gen Z first.' },
      { label: 'Value Local / Regional Brand Identity', value: '71%', icon: '📍', detail: 'Local relevance significantly increases purchase intent. Brands that localise content convert ~35% better with Gen Z.' },
      { label: 'Local Creator Trust Multiplier', value: '3×', icon: '🤝', detail: 'Gen Z trusts a local creator with 50K followers three times more than a global celebrity for purchase decisions.' },
    ],
    comparison: [
      { dimension: 'Trend Discovery',    global: 82, local: 45, note: 'Global internet surfaces trends first — viral moments travel at the speed of the algorithm' },
      { dimension: 'Purchase Intent',    global: 54, local: 78, note: 'Local relevance is the biggest conversion lever — hyper-local content drives buying decisions' },
      { dimension: 'Influencer Trust',   global: 51, local: 84, note: 'Local micro-creators feel like a friend, not a billboard — fundamentally different relationship' },
      { dimension: 'Brand Loyalty',      global: 60, local: 74, note: 'Community-rooted brands generate stronger, longer-lasting loyalty than global monoliths' },
      { dimension: 'Content Sharing',    global: 78, local: 58, note: 'Global viral content spreads faster — but local content drives deeper engagement per share' },
      { dimension: 'Cultural Alignment', global: 55, local: 81, note: 'Local cultural moments feel personal — global campaigns often feel generic or out of touch' },
    ],
    crocsInsight: 'Crocs has strong global brand recognition — a real advantage for trend discovery and awareness. But content strategy is inconsistent across local markets. Japan, Korea, Brazil, and Germany each have distinct Gen Z subcultures that respond to hyper-local creator content, not translated global campaigns. The brands winning Gen Z loyalty run centralised creative strategy with decentralised local execution.',
  },

  keyTakeaways: [
    { num: '01', icon: '🤝', color: '#43B02A', title: 'Build a Micro-Influencer Army, Not a Celebrity Roster', insight: 'Micro-influencers drive 87% purchase influence vs. 72% for mega-celebrities — at a fraction of the cost. Gen Z trusts people who look like them over untouchable stars.', action: 'Shift 40% of influencer budget from macro to micro partnerships. Target creators in Jibbitz-adjacent niches: customisation, cottagecore, K-pop fandom, sports lifestyle.' },
    { num: '02', icon: '🎬', color: '#EC4899', title: 'Invest in Micro-Drama & Episodic Branded Content', insight: 'Micro-dramas are the fastest-growing Gen Z content format — effectiveness at 64% and rising sharply in APAC. Crocs has untapped storytelling DNA for this format.', action: 'Commission a 6-episode TikTok series. Concept: "The Jibbitz Diaries" — different Gen Z characters expressing identity through Crocs customisation. Launch in JP and KR first.' },
    { num: '03', icon: '📍', color: '#3B82F6', title: 'Make Every Key Market Feel Like a Local Brand', insight: 'Local micro-influencers deliver 3× more purchase trust than global celebrities. 71% of Gen Z value local relevance. Most Crocs campaigns miss this conversion opportunity.', action: 'Launch a "Local Voices" programme — 5 micro-influencer partners per key market (JP, KR, IN, UK, FR, DE, BR). Give them Jibbitz kits and creative freedom, not brand scripts.' },
    { num: '04', icon: '⚡', color: '#F59E0B', title: 'Own the Algorithm, Not Just the Ad Slot', insight: 'Algorithm discovery influences 81% of Gen Z. Boosting organic content that already performs out-converts traditional ad creative by 3–5×. The feed is the media channel.', action: 'Implement a "Spark & Amplify" strategy: let UGC and creator content run organically for 24–48 hours, identify top performers, then deploy paid spend behind them.' },
    { num: '05', icon: '👁️', color: '#EF4444', title: 'The First 1.5 Seconds Are Everything', insight: 'In-feed ad skip rates are ~78%. Traditional ads score just 21% influence. But native short-form video scores 92% effectiveness. The hook is the campaign.', action: 'All paid creative must open with the most visually arresting frame — Jibbitz charm close-up, unexpected colourway pop, a reaction. No brand logos, no intros, no fade-ins.' },
    { num: '06', icon: '🦩', color: '#1D1D1B', title: 'Protect the Authenticity Advantage at All Costs', insight: 'Authenticity is Gen Z\'s #1 value at 94/100. Crocs\' willingness to be weird, meme-able and unapologetic is a rare brand asset that most heritage brands would kill for. Over-producing content will destroy it.', action: 'Establish a "Keep It Real" creative principle: one raw, creator-style social post for every produced campaign asset. Give the social team permission to post unpolished content.' },
  ],
};
